/*
 * generated by Xtext 2.17.0
 */
package edu.uoc.som.wot.td.json.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import edu.uoc.som.wot.td.json.ide.contentassist.antlr.internal.InternalThingDescriptionJsonParser;
import edu.uoc.som.wot.td.json.services.ThingDescriptionJsonGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class ThingDescriptionJsonParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(ThingDescriptionJsonGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, ThingDescriptionJsonGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getJsonThingAccess().getAlternatives_2_0_2(), "rule__JsonThing__Alternatives_2_0_2");
			builder.put(grammarAccess.getJsonThingAccess().getAlternatives_2_0_2_1_1(), "rule__JsonThing__Alternatives_2_0_2_1_1");
			builder.put(grammarAccess.getJsonThingAccess().getAlternatives_2_0_2_1_2_1(), "rule__JsonThing__Alternatives_2_0_2_1_2_1");
			builder.put(grammarAccess.getJsonThingAccess().getAlternatives_2_1_2(), "rule__JsonThing__Alternatives_2_1_2");
			builder.put(grammarAccess.getJsonThingAccess().getAlternatives_2_9_2(), "rule__JsonThing__Alternatives_2_9_2");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getAlternatives_4_1_2(), "rule__JsonPropertyAffordance__Alternatives_4_1_2");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getAlternatives_4_4_2(), "rule__JsonActionAffordance__Alternatives_4_4_2");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getAlternatives_4_3_2(), "rule__JsonEventAffordance__Alternatives_4_3_2");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getAlternatives_2_0_2(), "rule__JsonDataSchema__Alternatives_2_0_2");
			builder.put(grammarAccess.getJsonFormAccess().getAlternatives_2_0_2(), "rule__JsonForm__Alternatives_2_0_2");
			builder.put(grammarAccess.getJsonFormAccess().getAlternatives_2_1_2(), "rule__JsonForm__Alternatives_2_1_2");
			builder.put(grammarAccess.getJsonFormAccess().getAlternatives_2_6_2(), "rule__JsonForm__Alternatives_2_6_2");
			builder.put(grammarAccess.getJsonFormAccess().getAlternatives_2_7_2(), "rule__JsonForm__Alternatives_2_7_2");
			builder.put(grammarAccess.getJsonGenericExpressionAccess().getAlternatives(), "rule__JsonGenericExpression__Alternatives");
			builder.put(grammarAccess.getJsonGenericObjectAccess().getAlternatives(), "rule__JsonGenericObject__Alternatives");
			builder.put(grammarAccess.getJsonGenericArrayAccess().getAlternatives(), "rule__JsonGenericArray__Alternatives");
			builder.put(grammarAccess.getJsonPrimitiveValueAccess().getAlternatives(), "rule__JsonPrimitiveValue__Alternatives");
			builder.put(grammarAccess.getAnyStringAccess().getAlternatives(), "rule__AnyString__Alternatives");
			builder.put(grammarAccess.getKeywordAccess().getAlternatives(), "rule__Keyword__Alternatives");
			builder.put(grammarAccess.getJsonBooleanAccess().getAlternatives(), "rule__JsonBoolean__Alternatives");
			builder.put(grammarAccess.getJsonTypeAccess().getAlternatives(), "rule__JsonType__Alternatives");
			builder.put(grammarAccess.getJsonThingAccess().getGroup(), "rule__JsonThing__Group__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_0(), "rule__JsonThing__Group_2_0__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_0_2_1(), "rule__JsonThing__Group_2_0_2_1__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_0_2_1_2(), "rule__JsonThing__Group_2_0_2_1_2__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_1(), "rule__JsonThing__Group_2_1__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_1_2_1(), "rule__JsonThing__Group_2_1_2_1__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_1_2_1_2(), "rule__JsonThing__Group_2_1_2_1_2__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_2(), "rule__JsonThing__Group_2_2__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_3(), "rule__JsonThing__Group_2_3__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_4(), "rule__JsonThing__Group_2_4__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_5(), "rule__JsonThing__Group_2_5__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_6(), "rule__JsonThing__Group_2_6__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_7(), "rule__JsonThing__Group_2_7__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_8(), "rule__JsonThing__Group_2_8__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_9(), "rule__JsonThing__Group_2_9__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_9_2_1(), "rule__JsonThing__Group_2_9_2_1__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_9_2_1_2(), "rule__JsonThing__Group_2_9_2_1_2__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_10(), "rule__JsonThing__Group_2_10__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_10_4(), "rule__JsonThing__Group_2_10_4__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_11(), "rule__JsonThing__Group_2_11__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_11_4(), "rule__JsonThing__Group_2_11_4__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_12(), "rule__JsonThing__Group_2_12__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_12_4(), "rule__JsonThing__Group_2_12_4__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_13(), "rule__JsonThing__Group_2_13__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_13_4(), "rule__JsonThing__Group_2_13_4__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_14(), "rule__JsonThing__Group_2_14__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_15(), "rule__JsonThing__Group_2_15__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_15_4(), "rule__JsonThing__Group_2_15_4__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_16(), "rule__JsonThing__Group_2_16__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_16_4(), "rule__JsonThing__Group_2_16_4__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_17(), "rule__JsonThing__Group_2_17__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_17_4(), "rule__JsonThing__Group_2_17_4__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_18(), "rule__JsonThing__Group_2_18__0");
			builder.put(grammarAccess.getJsonThingAccess().getGroup_2_18_4(), "rule__JsonThing__Group_2_18_4__0");
			builder.put(grammarAccess.getJsonVersionInfoAccess().getGroup(), "rule__JsonVersionInfo__Group__0");
			builder.put(grammarAccess.getJsonSecuritySchemeAccess().getGroup(), "rule__JsonSecurityScheme__Group__0");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getGroup(), "rule__JsonPropertyAffordance__Group__0");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getGroup_4_0(), "rule__JsonPropertyAffordance__Group_4_0__0");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getGroup_4_1(), "rule__JsonPropertyAffordance__Group_4_1__0");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getGroup_4_1_2_1(), "rule__JsonPropertyAffordance__Group_4_1_2_1__0");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getGroup_4_1_2_1_2(), "rule__JsonPropertyAffordance__Group_4_1_2_1_2__0");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getGroup_4_2(), "rule__JsonPropertyAffordance__Group_4_2__0");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getGroup_4_3(), "rule__JsonPropertyAffordance__Group_4_3__0");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getGroup_4_4(), "rule__JsonPropertyAffordance__Group_4_4__0");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getGroup_4_4_4(), "rule__JsonPropertyAffordance__Group_4_4_4__0");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getGroup_4_5(), "rule__JsonPropertyAffordance__Group_4_5__0");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getGroup_4_5_4(), "rule__JsonPropertyAffordance__Group_4_5_4__0");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getGroup_4_6(), "rule__JsonPropertyAffordance__Group_4_6__0");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getGroup_4_6_4(), "rule__JsonPropertyAffordance__Group_4_6_4__0");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getGroup_4_7(), "rule__JsonPropertyAffordance__Group_4_7__0");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getGroup_4_7_4(), "rule__JsonPropertyAffordance__Group_4_7_4__0");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getGroup_4_8(), "rule__JsonPropertyAffordance__Group_4_8__0");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getGroup_4_9(), "rule__JsonPropertyAffordance__Group_4_9__0");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getGroup_4_10(), "rule__JsonPropertyAffordance__Group_4_10__0");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getGroup_4_11(), "rule__JsonPropertyAffordance__Group_4_11__0");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getGroup_4_11_4(), "rule__JsonPropertyAffordance__Group_4_11_4__0");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getGroup_4_12(), "rule__JsonPropertyAffordance__Group_4_12__0");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getGroup_4_13(), "rule__JsonPropertyAffordance__Group_4_13__0");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getGroup_4_14(), "rule__JsonPropertyAffordance__Group_4_14__0");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getGroup_4_15(), "rule__JsonPropertyAffordance__Group_4_15__0");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getGroup_4_15_4(), "rule__JsonPropertyAffordance__Group_4_15_4__0");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getGroup(), "rule__JsonActionAffordance__Group__0");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getGroup_4_0(), "rule__JsonActionAffordance__Group_4_0__0");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getGroup_4_1(), "rule__JsonActionAffordance__Group_4_1__0");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getGroup_4_2(), "rule__JsonActionAffordance__Group_4_2__0");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getGroup_4_3(), "rule__JsonActionAffordance__Group_4_3__0");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getGroup_4_4(), "rule__JsonActionAffordance__Group_4_4__0");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getGroup_4_4_2_1(), "rule__JsonActionAffordance__Group_4_4_2_1__0");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getGroup_4_4_2_1_2(), "rule__JsonActionAffordance__Group_4_4_2_1_2__0");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getGroup_4_5(), "rule__JsonActionAffordance__Group_4_5__0");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getGroup_4_6(), "rule__JsonActionAffordance__Group_4_6__0");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getGroup_4_7(), "rule__JsonActionAffordance__Group_4_7__0");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getGroup_4_7_4(), "rule__JsonActionAffordance__Group_4_7_4__0");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getGroup_4_8(), "rule__JsonActionAffordance__Group_4_8__0");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getGroup_4_8_4(), "rule__JsonActionAffordance__Group_4_8_4__0");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getGroup_4_9(), "rule__JsonActionAffordance__Group_4_9__0");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getGroup_4_9_4(), "rule__JsonActionAffordance__Group_4_9_4__0");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getGroup_4_10(), "rule__JsonActionAffordance__Group_4_10__0");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getGroup_4_10_4(), "rule__JsonActionAffordance__Group_4_10_4__0");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getGroup(), "rule__JsonEventAffordance__Group__0");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getGroup_4_0(), "rule__JsonEventAffordance__Group_4_0__0");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getGroup_4_1(), "rule__JsonEventAffordance__Group_4_1__0");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getGroup_4_2(), "rule__JsonEventAffordance__Group_4_2__0");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getGroup_4_3(), "rule__JsonEventAffordance__Group_4_3__0");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getGroup_4_3_2_1(), "rule__JsonEventAffordance__Group_4_3_2_1__0");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getGroup_4_3_2_1_2(), "rule__JsonEventAffordance__Group_4_3_2_1_2__0");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getGroup_4_4(), "rule__JsonEventAffordance__Group_4_4__0");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getGroup_4_5(), "rule__JsonEventAffordance__Group_4_5__0");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getGroup_4_6(), "rule__JsonEventAffordance__Group_4_6__0");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getGroup_4_6_4(), "rule__JsonEventAffordance__Group_4_6_4__0");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getGroup_4_7(), "rule__JsonEventAffordance__Group_4_7__0");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getGroup_4_7_4(), "rule__JsonEventAffordance__Group_4_7_4__0");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getGroup_4_8(), "rule__JsonEventAffordance__Group_4_8__0");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getGroup_4_8_4(), "rule__JsonEventAffordance__Group_4_8_4__0");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getGroup_4_9(), "rule__JsonEventAffordance__Group_4_9__0");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getGroup_4_9_4(), "rule__JsonEventAffordance__Group_4_9_4__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup(), "rule__JsonDataSchema__Group__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_0(), "rule__JsonDataSchema__Group_2_0__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_0_2_1(), "rule__JsonDataSchema__Group_2_0_2_1__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_0_2_1_2(), "rule__JsonDataSchema__Group_2_0_2_1_2__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_1(), "rule__JsonDataSchema__Group_2_1__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_2(), "rule__JsonDataSchema__Group_2_2__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_3(), "rule__JsonDataSchema__Group_2_3__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_4(), "rule__JsonDataSchema__Group_2_4__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_5(), "rule__JsonDataSchema__Group_2_5__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_6(), "rule__JsonDataSchema__Group_2_6__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_6_4(), "rule__JsonDataSchema__Group_2_6_4__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_7(), "rule__JsonDataSchema__Group_2_7__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_8(), "rule__JsonDataSchema__Group_2_8__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_9(), "rule__JsonDataSchema__Group_2_9__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_10(), "rule__JsonDataSchema__Group_2_10__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_10_4(), "rule__JsonDataSchema__Group_2_10_4__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_11(), "rule__JsonDataSchema__Group_2_11__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_11_4(), "rule__JsonDataSchema__Group_2_11_4__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_12(), "rule__JsonDataSchema__Group_2_12__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_12_4(), "rule__JsonDataSchema__Group_2_12_4__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_13(), "rule__JsonDataSchema__Group_2_13__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_14(), "rule__JsonDataSchema__Group_2_14__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_15(), "rule__JsonDataSchema__Group_2_15__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_15_4(), "rule__JsonDataSchema__Group_2_15_4__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_16(), "rule__JsonDataSchema__Group_2_16__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_16_4(), "rule__JsonDataSchema__Group_2_16_4__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_17(), "rule__JsonDataSchema__Group_2_17__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_17_4(), "rule__JsonDataSchema__Group_2_17_4__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_18(), "rule__JsonDataSchema__Group_2_18__0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getGroup_2_19(), "rule__JsonDataSchema__Group_2_19__0");
			builder.put(grammarAccess.getJsonLinkAccess().getGroup(), "rule__JsonLink__Group__0");
			builder.put(grammarAccess.getJsonLinkAccess().getGroup_2_0(), "rule__JsonLink__Group_2_0__0");
			builder.put(grammarAccess.getJsonLinkAccess().getGroup_2_1(), "rule__JsonLink__Group_2_1__0");
			builder.put(grammarAccess.getJsonLinkAccess().getGroup_2_2(), "rule__JsonLink__Group_2_2__0");
			builder.put(grammarAccess.getJsonLinkAccess().getGroup_2_3(), "rule__JsonLink__Group_2_3__0");
			builder.put(grammarAccess.getJsonFormAccess().getGroup(), "rule__JsonForm__Group__0");
			builder.put(grammarAccess.getJsonFormAccess().getGroup_2_0(), "rule__JsonForm__Group_2_0__0");
			builder.put(grammarAccess.getJsonFormAccess().getGroup_2_0_2_1(), "rule__JsonForm__Group_2_0_2_1__0");
			builder.put(grammarAccess.getJsonFormAccess().getGroup_2_0_2_1_2(), "rule__JsonForm__Group_2_0_2_1_2__0");
			builder.put(grammarAccess.getJsonFormAccess().getGroup_2_1(), "rule__JsonForm__Group_2_1__0");
			builder.put(grammarAccess.getJsonFormAccess().getGroup_2_1_2_1(), "rule__JsonForm__Group_2_1_2_1__0");
			builder.put(grammarAccess.getJsonFormAccess().getGroup_2_1_2_1_2(), "rule__JsonForm__Group_2_1_2_1_2__0");
			builder.put(grammarAccess.getJsonFormAccess().getGroup_2_2(), "rule__JsonForm__Group_2_2__0");
			builder.put(grammarAccess.getJsonFormAccess().getGroup_2_3(), "rule__JsonForm__Group_2_3__0");
			builder.put(grammarAccess.getJsonFormAccess().getGroup_2_4(), "rule__JsonForm__Group_2_4__0");
			builder.put(grammarAccess.getJsonFormAccess().getGroup_2_5(), "rule__JsonForm__Group_2_5__0");
			builder.put(grammarAccess.getJsonFormAccess().getGroup_2_6(), "rule__JsonForm__Group_2_6__0");
			builder.put(grammarAccess.getJsonFormAccess().getGroup_2_6_2_1(), "rule__JsonForm__Group_2_6_2_1__0");
			builder.put(grammarAccess.getJsonFormAccess().getGroup_2_6_2_1_2(), "rule__JsonForm__Group_2_6_2_1_2__0");
			builder.put(grammarAccess.getJsonFormAccess().getGroup_2_7(), "rule__JsonForm__Group_2_7__0");
			builder.put(grammarAccess.getJsonFormAccess().getGroup_2_7_2_1(), "rule__JsonForm__Group_2_7_2_1__0");
			builder.put(grammarAccess.getJsonFormAccess().getGroup_2_7_2_1_2(), "rule__JsonForm__Group_2_7_2_1_2__0");
			builder.put(grammarAccess.getJsonFormAccess().getGroup_2_8(), "rule__JsonForm__Group_2_8__0");
			builder.put(grammarAccess.getJsonExpectedResponseAccess().getGroup(), "rule__JsonExpectedResponse__Group__0");
			builder.put(grammarAccess.getJsonMultiLanguageEntryAccess().getGroup(), "rule__JsonMultiLanguageEntry__Group__0");
			builder.put(grammarAccess.getJsonGenericObjectAccess().getGroup_0(), "rule__JsonGenericObject__Group_0__0");
			builder.put(grammarAccess.getJsonGenericObjectAccess().getGroup_1(), "rule__JsonGenericObject__Group_1__0");
			builder.put(grammarAccess.getJsonGenericObjectAccess().getGroup_1_2(), "rule__JsonGenericObject__Group_1_2__0");
			builder.put(grammarAccess.getJsonGenericArrayAccess().getGroup_0(), "rule__JsonGenericArray__Group_0__0");
			builder.put(grammarAccess.getJsonGenericArrayAccess().getGroup_1(), "rule__JsonGenericArray__Group_1__0");
			builder.put(grammarAccess.getJsonGenericArrayAccess().getGroup_1_2(), "rule__JsonGenericArray__Group_1_2__0");
			builder.put(grammarAccess.getJsonGenericTupleAccess().getGroup(), "rule__JsonGenericTuple__Group__0");
			builder.put(grammarAccess.getJsonThingAccess().getLd_contextAssignment_2_0_2_0(), "rule__JsonThing__Ld_contextAssignment_2_0_2_0");
			builder.put(grammarAccess.getJsonThingAccess().getLd_contextAssignment_2_0_2_1_1_0(), "rule__JsonThing__Ld_contextAssignment_2_0_2_1_1_0");
			builder.put(grammarAccess.getJsonThingAccess().getLd_contextAssignment_2_0_2_1_2_1_0(), "rule__JsonThing__Ld_contextAssignment_2_0_2_1_2_1_0");
			builder.put(grammarAccess.getJsonThingAccess().getLd_typeAssignment_2_1_2_0(), "rule__JsonThing__Ld_typeAssignment_2_1_2_0");
			builder.put(grammarAccess.getJsonThingAccess().getLd_typeAssignment_2_1_2_1_1(), "rule__JsonThing__Ld_typeAssignment_2_1_2_1_1");
			builder.put(grammarAccess.getJsonThingAccess().getLd_typeAssignment_2_1_2_1_2_1(), "rule__JsonThing__Ld_typeAssignment_2_1_2_1_2_1");
			builder.put(grammarAccess.getJsonThingAccess().getIdAssignment_2_2_2(), "rule__JsonThing__IdAssignment_2_2_2");
			builder.put(grammarAccess.getJsonThingAccess().getTitleAssignment_2_3_2(), "rule__JsonThing__TitleAssignment_2_3_2");
			builder.put(grammarAccess.getJsonThingAccess().getDescriptionAssignment_2_4_2(), "rule__JsonThing__DescriptionAssignment_2_4_2");
			builder.put(grammarAccess.getJsonThingAccess().getCreatedAssignment_2_5_2(), "rule__JsonThing__CreatedAssignment_2_5_2");
			builder.put(grammarAccess.getJsonThingAccess().getModifiedAssignment_2_6_2(), "rule__JsonThing__ModifiedAssignment_2_6_2");
			builder.put(grammarAccess.getJsonThingAccess().getSupportAssignment_2_7_2(), "rule__JsonThing__SupportAssignment_2_7_2");
			builder.put(grammarAccess.getJsonThingAccess().getBaseAssignment_2_8_2(), "rule__JsonThing__BaseAssignment_2_8_2");
			builder.put(grammarAccess.getJsonThingAccess().getSecurityAssignment_2_9_2_0(), "rule__JsonThing__SecurityAssignment_2_9_2_0");
			builder.put(grammarAccess.getJsonThingAccess().getSecurityAssignment_2_9_2_1_1(), "rule__JsonThing__SecurityAssignment_2_9_2_1_1");
			builder.put(grammarAccess.getJsonThingAccess().getSecurityAssignment_2_9_2_1_2_1(), "rule__JsonThing__SecurityAssignment_2_9_2_1_2_1");
			builder.put(grammarAccess.getJsonThingAccess().getFormsAssignment_2_10_3(), "rule__JsonThing__FormsAssignment_2_10_3");
			builder.put(grammarAccess.getJsonThingAccess().getFormsAssignment_2_10_4_1(), "rule__JsonThing__FormsAssignment_2_10_4_1");
			builder.put(grammarAccess.getJsonThingAccess().getLinksAssignment_2_11_3(), "rule__JsonThing__LinksAssignment_2_11_3");
			builder.put(grammarAccess.getJsonThingAccess().getLinksAssignment_2_11_4_1(), "rule__JsonThing__LinksAssignment_2_11_4_1");
			builder.put(grammarAccess.getJsonThingAccess().getTitlesAssignment_2_12_3(), "rule__JsonThing__TitlesAssignment_2_12_3");
			builder.put(grammarAccess.getJsonThingAccess().getTitlesAssignment_2_12_4_1(), "rule__JsonThing__TitlesAssignment_2_12_4_1");
			builder.put(grammarAccess.getJsonThingAccess().getDescriptionsAssignment_2_13_3(), "rule__JsonThing__DescriptionsAssignment_2_13_3");
			builder.put(grammarAccess.getJsonThingAccess().getDescriptionsAssignment_2_13_4_1(), "rule__JsonThing__DescriptionsAssignment_2_13_4_1");
			builder.put(grammarAccess.getJsonThingAccess().getVersionAssignment_2_14_2(), "rule__JsonThing__VersionAssignment_2_14_2");
			builder.put(grammarAccess.getJsonThingAccess().getPropertiesAssignment_2_15_3(), "rule__JsonThing__PropertiesAssignment_2_15_3");
			builder.put(grammarAccess.getJsonThingAccess().getPropertiesAssignment_2_15_4_1(), "rule__JsonThing__PropertiesAssignment_2_15_4_1");
			builder.put(grammarAccess.getJsonThingAccess().getActionsAssignment_2_16_3(), "rule__JsonThing__ActionsAssignment_2_16_3");
			builder.put(grammarAccess.getJsonThingAccess().getActionsAssignment_2_16_4_1(), "rule__JsonThing__ActionsAssignment_2_16_4_1");
			builder.put(grammarAccess.getJsonThingAccess().getEventsAssignment_2_17_3(), "rule__JsonThing__EventsAssignment_2_17_3");
			builder.put(grammarAccess.getJsonThingAccess().getEventsAssignment_2_17_4_1(), "rule__JsonThing__EventsAssignment_2_17_4_1");
			builder.put(grammarAccess.getJsonThingAccess().getSecurityDefinitionsAssignment_2_18_3(), "rule__JsonThing__SecurityDefinitionsAssignment_2_18_3");
			builder.put(grammarAccess.getJsonThingAccess().getSecurityDefinitionsAssignment_2_18_4_1(), "rule__JsonThing__SecurityDefinitionsAssignment_2_18_4_1");
			builder.put(grammarAccess.getJsonVersionInfoAccess().getInstanceAssignment_4(), "rule__JsonVersionInfo__InstanceAssignment_4");
			builder.put(grammarAccess.getJsonSecuritySchemeAccess().getIdAssignment_1(), "rule__JsonSecurityScheme__IdAssignment_1");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getIdAssignment_1(), "rule__JsonPropertyAffordance__IdAssignment_1");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getObservableAssignment_4_0_2(), "rule__JsonPropertyAffordance__ObservableAssignment_4_0_2");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getLd_typeAssignment_4_1_2_0(), "rule__JsonPropertyAffordance__Ld_typeAssignment_4_1_2_0");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getLd_typeAssignment_4_1_2_1_1(), "rule__JsonPropertyAffordance__Ld_typeAssignment_4_1_2_1_1");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getLd_typeAssignment_4_1_2_1_2_1(), "rule__JsonPropertyAffordance__Ld_typeAssignment_4_1_2_1_2_1");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getTitleAssignment_4_2_2(), "rule__JsonPropertyAffordance__TitleAssignment_4_2_2");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getDescriptionAssignment_4_3_2(), "rule__JsonPropertyAffordance__DescriptionAssignment_4_3_2");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getTitlesAssignment_4_4_3(), "rule__JsonPropertyAffordance__TitlesAssignment_4_4_3");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getTitlesAssignment_4_4_4_1(), "rule__JsonPropertyAffordance__TitlesAssignment_4_4_4_1");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getDescriptionsAssignment_4_5_3(), "rule__JsonPropertyAffordance__DescriptionsAssignment_4_5_3");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getDescriptionsAssignment_4_5_4_1(), "rule__JsonPropertyAffordance__DescriptionsAssignment_4_5_4_1");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getFormsAssignment_4_6_3(), "rule__JsonPropertyAffordance__FormsAssignment_4_6_3");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getFormsAssignment_4_6_4_1(), "rule__JsonPropertyAffordance__FormsAssignment_4_6_4_1");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getUriVariableAssignment_4_7_3(), "rule__JsonPropertyAffordance__UriVariableAssignment_4_7_3");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getUriVariableAssignment_4_7_4_1(), "rule__JsonPropertyAffordance__UriVariableAssignment_4_7_4_1");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getTypeAssignment_4_8_2(), "rule__JsonPropertyAffordance__TypeAssignment_4_8_2");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getConstAssignment_4_9_2(), "rule__JsonPropertyAffordance__ConstAssignment_4_9_2");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getUnitAssignment_4_10_2(), "rule__JsonPropertyAffordance__UnitAssignment_4_10_2");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getEnumAssignment_4_11_3(), "rule__JsonPropertyAffordance__EnumAssignment_4_11_3");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getEnumAssignment_4_11_4_1(), "rule__JsonPropertyAffordance__EnumAssignment_4_11_4_1");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getReadOnlyAssignment_4_12_2(), "rule__JsonPropertyAffordance__ReadOnlyAssignment_4_12_2");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getWriteOnlyAssignment_4_13_2(), "rule__JsonPropertyAffordance__WriteOnlyAssignment_4_13_2");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getFormatAssignment_4_14_2(), "rule__JsonPropertyAffordance__FormatAssignment_4_14_2");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getOneOfAssignment_4_15_3(), "rule__JsonPropertyAffordance__OneOfAssignment_4_15_3");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getOneOfAssignment_4_15_4_1(), "rule__JsonPropertyAffordance__OneOfAssignment_4_15_4_1");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getIdAssignment_1(), "rule__JsonActionAffordance__IdAssignment_1");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getSafeAssignment_4_0_2(), "rule__JsonActionAffordance__SafeAssignment_4_0_2");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getIdempotentAssignment_4_1_2(), "rule__JsonActionAffordance__IdempotentAssignment_4_1_2");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getInputAssignment_4_2_2(), "rule__JsonActionAffordance__InputAssignment_4_2_2");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getOutputAssignment_4_3_2(), "rule__JsonActionAffordance__OutputAssignment_4_3_2");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getLd_typeAssignment_4_4_2_0(), "rule__JsonActionAffordance__Ld_typeAssignment_4_4_2_0");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getLd_typeAssignment_4_4_2_1_1(), "rule__JsonActionAffordance__Ld_typeAssignment_4_4_2_1_1");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getLd_typeAssignment_4_4_2_1_2_1(), "rule__JsonActionAffordance__Ld_typeAssignment_4_4_2_1_2_1");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getTitleAssignment_4_5_2(), "rule__JsonActionAffordance__TitleAssignment_4_5_2");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getDescriptionAssignment_4_6_2(), "rule__JsonActionAffordance__DescriptionAssignment_4_6_2");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getFormsAssignment_4_7_3(), "rule__JsonActionAffordance__FormsAssignment_4_7_3");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getFormsAssignment_4_7_4_1(), "rule__JsonActionAffordance__FormsAssignment_4_7_4_1");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getTitlesAssignment_4_8_3(), "rule__JsonActionAffordance__TitlesAssignment_4_8_3");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getTitlesAssignment_4_8_4_1(), "rule__JsonActionAffordance__TitlesAssignment_4_8_4_1");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getDescriptionsAssignment_4_9_3(), "rule__JsonActionAffordance__DescriptionsAssignment_4_9_3");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getDescriptionsAssignment_4_9_4_1(), "rule__JsonActionAffordance__DescriptionsAssignment_4_9_4_1");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getUriVariableAssignment_4_10_3(), "rule__JsonActionAffordance__UriVariableAssignment_4_10_3");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getUriVariableAssignment_4_10_4_1(), "rule__JsonActionAffordance__UriVariableAssignment_4_10_4_1");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getIdAssignment_1(), "rule__JsonEventAffordance__IdAssignment_1");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getDataAssignment_4_0_2(), "rule__JsonEventAffordance__DataAssignment_4_0_2");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getSubscriptionAssignment_4_1_2(), "rule__JsonEventAffordance__SubscriptionAssignment_4_1_2");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getCancellationAssignment_4_2_2(), "rule__JsonEventAffordance__CancellationAssignment_4_2_2");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getLd_typeAssignment_4_3_2_0(), "rule__JsonEventAffordance__Ld_typeAssignment_4_3_2_0");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getLd_typeAssignment_4_3_2_1_1(), "rule__JsonEventAffordance__Ld_typeAssignment_4_3_2_1_1");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getLd_typeAssignment_4_3_2_1_2_1(), "rule__JsonEventAffordance__Ld_typeAssignment_4_3_2_1_2_1");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getTitleAssignment_4_4_2(), "rule__JsonEventAffordance__TitleAssignment_4_4_2");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getDescriptionAssignment_4_5_2(), "rule__JsonEventAffordance__DescriptionAssignment_4_5_2");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getFormsAssignment_4_6_3(), "rule__JsonEventAffordance__FormsAssignment_4_6_3");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getFormsAssignment_4_6_4_1(), "rule__JsonEventAffordance__FormsAssignment_4_6_4_1");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getTitlesAssignment_4_7_3(), "rule__JsonEventAffordance__TitlesAssignment_4_7_3");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getTitlesAssignment_4_7_4_1(), "rule__JsonEventAffordance__TitlesAssignment_4_7_4_1");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getDescriptionsAssignment_4_8_3(), "rule__JsonEventAffordance__DescriptionsAssignment_4_8_3");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getDescriptionsAssignment_4_8_4_1(), "rule__JsonEventAffordance__DescriptionsAssignment_4_8_4_1");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getUriVariableAssignment_4_9_3(), "rule__JsonEventAffordance__UriVariableAssignment_4_9_3");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getUriVariableAssignment_4_9_4_1(), "rule__JsonEventAffordance__UriVariableAssignment_4_9_4_1");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getLd_typeAssignment_2_0_2_0(), "rule__JsonDataSchema__Ld_typeAssignment_2_0_2_0");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getLd_typeAssignment_2_0_2_1_1(), "rule__JsonDataSchema__Ld_typeAssignment_2_0_2_1_1");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getLd_typeAssignment_2_0_2_1_2_1(), "rule__JsonDataSchema__Ld_typeAssignment_2_0_2_1_2_1");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getTitleAssignment_2_1_2(), "rule__JsonDataSchema__TitleAssignment_2_1_2");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getDescriptionAssignment_2_2_2(), "rule__JsonDataSchema__DescriptionAssignment_2_2_2");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getTypeAssignment_2_3_2(), "rule__JsonDataSchema__TypeAssignment_2_3_2");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getConstAssignment_2_4_2(), "rule__JsonDataSchema__ConstAssignment_2_4_2");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getUnitAssignment_2_5_2(), "rule__JsonDataSchema__UnitAssignment_2_5_2");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getEnumAssignment_2_6_3(), "rule__JsonDataSchema__EnumAssignment_2_6_3");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getEnumAssignment_2_6_4_1(), "rule__JsonDataSchema__EnumAssignment_2_6_4_1");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getReadOnlyAssignment_2_7_2(), "rule__JsonDataSchema__ReadOnlyAssignment_2_7_2");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getWriteOnlyAssignment_2_8_2(), "rule__JsonDataSchema__WriteOnlyAssignment_2_8_2");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getFormatAssignment_2_9_2(), "rule__JsonDataSchema__FormatAssignment_2_9_2");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getOneOfAssignment_2_10_3(), "rule__JsonDataSchema__OneOfAssignment_2_10_3");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getOneOfAssignment_2_10_4_1(), "rule__JsonDataSchema__OneOfAssignment_2_10_4_1");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getTitlesAssignment_2_11_3(), "rule__JsonDataSchema__TitlesAssignment_2_11_3");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getTitlesAssignment_2_11_4_1(), "rule__JsonDataSchema__TitlesAssignment_2_11_4_1");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getDescriptionsAssignment_2_12_3(), "rule__JsonDataSchema__DescriptionsAssignment_2_12_3");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getDescriptionsAssignment_2_12_4_1(), "rule__JsonDataSchema__DescriptionsAssignment_2_12_4_1");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getMinItemsAssignment_2_13_2(), "rule__JsonDataSchema__MinItemsAssignment_2_13_2");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getMaxItemsAssignment_2_14_2(), "rule__JsonDataSchema__MaxItemsAssignment_2_14_2");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getItemsAssignment_2_15_3(), "rule__JsonDataSchema__ItemsAssignment_2_15_3");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getItemsAssignment_2_15_4_1(), "rule__JsonDataSchema__ItemsAssignment_2_15_4_1");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getRequiredAssignment_2_16_3(), "rule__JsonDataSchema__RequiredAssignment_2_16_3");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getRequiredAssignment_2_16_4_1(), "rule__JsonDataSchema__RequiredAssignment_2_16_4_1");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getPropertiesAssignment_2_17_3(), "rule__JsonDataSchema__PropertiesAssignment_2_17_3");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getPropertiesAssignment_2_17_4_1(), "rule__JsonDataSchema__PropertiesAssignment_2_17_4_1");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getMinimumAssignment_2_18_2(), "rule__JsonDataSchema__MinimumAssignment_2_18_2");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getMaximumAssignment_2_19_2(), "rule__JsonDataSchema__MaximumAssignment_2_19_2");
			builder.put(grammarAccess.getJsonLinkAccess().get_hrefAssignment_2_0_2(), "rule__JsonLink___hrefAssignment_2_0_2");
			builder.put(grammarAccess.getJsonLinkAccess().getTypeAssignment_2_1_2(), "rule__JsonLink__TypeAssignment_2_1_2");
			builder.put(grammarAccess.getJsonLinkAccess().getRelAssignment_2_2_2(), "rule__JsonLink__RelAssignment_2_2_2");
			builder.put(grammarAccess.getJsonLinkAccess().getAnchorAssignment_2_3_2(), "rule__JsonLink__AnchorAssignment_2_3_2");
			builder.put(grammarAccess.getJsonFormAccess().getLd_typeAssignment_2_0_2_0(), "rule__JsonForm__Ld_typeAssignment_2_0_2_0");
			builder.put(grammarAccess.getJsonFormAccess().getLd_typeAssignment_2_0_2_1_1(), "rule__JsonForm__Ld_typeAssignment_2_0_2_1_1");
			builder.put(grammarAccess.getJsonFormAccess().getLd_typeAssignment_2_0_2_1_2_1(), "rule__JsonForm__Ld_typeAssignment_2_0_2_1_2_1");
			builder.put(grammarAccess.getJsonFormAccess().getOpAssignment_2_1_2_0(), "rule__JsonForm__OpAssignment_2_1_2_0");
			builder.put(grammarAccess.getJsonFormAccess().getOpAssignment_2_1_2_1_1(), "rule__JsonForm__OpAssignment_2_1_2_1_1");
			builder.put(grammarAccess.getJsonFormAccess().getOpAssignment_2_1_2_1_2_1(), "rule__JsonForm__OpAssignment_2_1_2_1_2_1");
			builder.put(grammarAccess.getJsonFormAccess().get_hrefAssignment_2_2_2(), "rule__JsonForm___hrefAssignment_2_2_2");
			builder.put(grammarAccess.getJsonFormAccess().getContentTypeAssignment_2_3_2(), "rule__JsonForm__ContentTypeAssignment_2_3_2");
			builder.put(grammarAccess.getJsonFormAccess().getContentCodingAssignment_2_4_2(), "rule__JsonForm__ContentCodingAssignment_2_4_2");
			builder.put(grammarAccess.getJsonFormAccess().getSubprotocolAssignment_2_5_2(), "rule__JsonForm__SubprotocolAssignment_2_5_2");
			builder.put(grammarAccess.getJsonFormAccess().getSecurityAssignment_2_6_2_0(), "rule__JsonForm__SecurityAssignment_2_6_2_0");
			builder.put(grammarAccess.getJsonFormAccess().getSecurityAssignment_2_6_2_1_1(), "rule__JsonForm__SecurityAssignment_2_6_2_1_1");
			builder.put(grammarAccess.getJsonFormAccess().getSecurityAssignment_2_6_2_1_2_1(), "rule__JsonForm__SecurityAssignment_2_6_2_1_2_1");
			builder.put(grammarAccess.getJsonFormAccess().getScopesAssignment_2_7_2_0(), "rule__JsonForm__ScopesAssignment_2_7_2_0");
			builder.put(grammarAccess.getJsonFormAccess().getScopesAssignment_2_7_2_1_1(), "rule__JsonForm__ScopesAssignment_2_7_2_1_1");
			builder.put(grammarAccess.getJsonFormAccess().getScopesAssignment_2_7_2_1_2_1(), "rule__JsonForm__ScopesAssignment_2_7_2_1_2_1");
			builder.put(grammarAccess.getJsonFormAccess().getResponseAssignment_2_8_2(), "rule__JsonForm__ResponseAssignment_2_8_2");
			builder.put(grammarAccess.getJsonExpectedResponseAccess().getContentTypeAssignment_4(), "rule__JsonExpectedResponse__ContentTypeAssignment_4");
			builder.put(grammarAccess.getJsonMultiLanguageEntryAccess().getLanguageAssignment_1(), "rule__JsonMultiLanguageEntry__LanguageAssignment_1");
			builder.put(grammarAccess.getJsonMultiLanguageEntryAccess().getContentAssignment_3(), "rule__JsonMultiLanguageEntry__ContentAssignment_3");
			builder.put(grammarAccess.getJsonThingAccess().getUnorderedGroup_2(), "rule__JsonThing__UnorderedGroup_2");
			builder.put(grammarAccess.getJsonPropertyAffordanceAccess().getUnorderedGroup_4(), "rule__JsonPropertyAffordance__UnorderedGroup_4");
			builder.put(grammarAccess.getJsonActionAffordanceAccess().getUnorderedGroup_4(), "rule__JsonActionAffordance__UnorderedGroup_4");
			builder.put(grammarAccess.getJsonEventAffordanceAccess().getUnorderedGroup_4(), "rule__JsonEventAffordance__UnorderedGroup_4");
			builder.put(grammarAccess.getJsonDataSchemaAccess().getUnorderedGroup_2(), "rule__JsonDataSchema__UnorderedGroup_2");
			builder.put(grammarAccess.getJsonLinkAccess().getUnorderedGroup_2(), "rule__JsonLink__UnorderedGroup_2");
			builder.put(grammarAccess.getJsonFormAccess().getUnorderedGroup_2(), "rule__JsonForm__UnorderedGroup_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private ThingDescriptionJsonGrammarAccess grammarAccess;

	@Override
	protected InternalThingDescriptionJsonParser createParser() {
		InternalThingDescriptionJsonParser result = new InternalThingDescriptionJsonParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS" };
	}

	public ThingDescriptionJsonGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ThingDescriptionJsonGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
