/*
 * generated by Xtext 2.17.0
 */
package edu.uoc.som.wot.td.json.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ThingDescriptionJsonProposalProvider extends AbstractThingDescriptionJsonProposalProvider {
}
