/*
 * generated by Xtext 2.17.0
 */
package edu.uoc.som.wot.td.json.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class ThingDescriptionJsonUiModule extends AbstractThingDescriptionJsonUiModule {
}
