/*
 * generated by Xtext 2.17.0
 */
package edu.uoc.som.wot.td.json.ide


/**
 * Use this class to register ide components.
 */
class ThingDescriptionJsonIdeModule extends AbstractThingDescriptionJsonIdeModule {
}
