/**
 * generated by Xtext 2.17.0
 */
package edu.uoc.som.wot.td.json.thingDescriptionJson.impl;

import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema;
import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonEventAffordance;
import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonForm;
import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonMultiLanguageEntry;
import edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Json Event Affordance</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonEventAffordanceImpl#getId <em>Id</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonEventAffordanceImpl#getData <em>Data</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonEventAffordanceImpl#getSubscription <em>Subscription</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonEventAffordanceImpl#getCancellation <em>Cancellation</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonEventAffordanceImpl#getLd_type <em>Ld type</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonEventAffordanceImpl#getTitle <em>Title</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonEventAffordanceImpl#getDescription <em>Description</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonEventAffordanceImpl#getForms <em>Forms</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonEventAffordanceImpl#getTitles <em>Titles</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonEventAffordanceImpl#getDescriptions <em>Descriptions</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonEventAffordanceImpl#getUriVariable <em>Uri Variable</em>}</li>
 * </ul>
 *
 * @generated
 */
public class JsonEventAffordanceImpl extends MinimalEObjectImpl.Container implements JsonEventAffordance
{
  /**
   * The default value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected static final String ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected String id = ID_EDEFAULT;

  /**
   * The cached value of the '{@link #getData() <em>Data</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getData()
   * @generated
   * @ordered
   */
  protected JsonDataSchema data;

  /**
   * The cached value of the '{@link #getSubscription() <em>Subscription</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubscription()
   * @generated
   * @ordered
   */
  protected JsonDataSchema subscription;

  /**
   * The cached value of the '{@link #getCancellation() <em>Cancellation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCancellation()
   * @generated
   * @ordered
   */
  protected JsonDataSchema cancellation;

  /**
   * The cached value of the '{@link #getLd_type() <em>Ld type</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLd_type()
   * @generated
   * @ordered
   */
  protected EList<String> ld_type;

  /**
   * The default value of the '{@link #getTitle() <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitle()
   * @generated
   * @ordered
   */
  protected static final String TITLE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTitle() <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitle()
   * @generated
   * @ordered
   */
  protected String title = TITLE_EDEFAULT;

  /**
   * The default value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected static final String DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected String description = DESCRIPTION_EDEFAULT;

  /**
   * The cached value of the '{@link #getForms() <em>Forms</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getForms()
   * @generated
   * @ordered
   */
  protected EList<JsonForm> forms;

  /**
   * The cached value of the '{@link #getTitles() <em>Titles</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitles()
   * @generated
   * @ordered
   */
  protected EList<JsonMultiLanguageEntry> titles;

  /**
   * The cached value of the '{@link #getDescriptions() <em>Descriptions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescriptions()
   * @generated
   * @ordered
   */
  protected EList<JsonMultiLanguageEntry> descriptions;

  /**
   * The cached value of the '{@link #getUriVariable() <em>Uri Variable</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUriVariable()
   * @generated
   * @ordered
   */
  protected EList<JsonDataSchema> uriVariable;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JsonEventAffordanceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThingDescriptionJsonPackage.Literals.JSON_EVENT_AFFORDANCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getId()
  {
    return id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setId(String newId)
  {
    String oldId = id;
    id = newId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__ID, oldId, id));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JsonDataSchema getData()
  {
    return data;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetData(JsonDataSchema newData, NotificationChain msgs)
  {
    JsonDataSchema oldData = data;
    data = newData;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__DATA, oldData, newData);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setData(JsonDataSchema newData)
  {
    if (newData != data)
    {
      NotificationChain msgs = null;
      if (data != null)
        msgs = ((InternalEObject)data).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__DATA, null, msgs);
      if (newData != null)
        msgs = ((InternalEObject)newData).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__DATA, null, msgs);
      msgs = basicSetData(newData, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__DATA, newData, newData));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JsonDataSchema getSubscription()
  {
    return subscription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSubscription(JsonDataSchema newSubscription, NotificationChain msgs)
  {
    JsonDataSchema oldSubscription = subscription;
    subscription = newSubscription;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__SUBSCRIPTION, oldSubscription, newSubscription);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSubscription(JsonDataSchema newSubscription)
  {
    if (newSubscription != subscription)
    {
      NotificationChain msgs = null;
      if (subscription != null)
        msgs = ((InternalEObject)subscription).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__SUBSCRIPTION, null, msgs);
      if (newSubscription != null)
        msgs = ((InternalEObject)newSubscription).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__SUBSCRIPTION, null, msgs);
      msgs = basicSetSubscription(newSubscription, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__SUBSCRIPTION, newSubscription, newSubscription));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JsonDataSchema getCancellation()
  {
    return cancellation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCancellation(JsonDataSchema newCancellation, NotificationChain msgs)
  {
    JsonDataSchema oldCancellation = cancellation;
    cancellation = newCancellation;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__CANCELLATION, oldCancellation, newCancellation);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCancellation(JsonDataSchema newCancellation)
  {
    if (newCancellation != cancellation)
    {
      NotificationChain msgs = null;
      if (cancellation != null)
        msgs = ((InternalEObject)cancellation).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__CANCELLATION, null, msgs);
      if (newCancellation != null)
        msgs = ((InternalEObject)newCancellation).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__CANCELLATION, null, msgs);
      msgs = basicSetCancellation(newCancellation, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__CANCELLATION, newCancellation, newCancellation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getLd_type()
  {
    if (ld_type == null)
    {
      ld_type = new EDataTypeEList<String>(String.class, this, ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__LD_TYPE);
    }
    return ld_type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTitle()
  {
    return title;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTitle(String newTitle)
  {
    String oldTitle = title;
    title = newTitle;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__TITLE, oldTitle, title));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDescription()
  {
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDescription(String newDescription)
  {
    String oldDescription = description;
    description = newDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__DESCRIPTION, oldDescription, description));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<JsonForm> getForms()
  {
    if (forms == null)
    {
      forms = new EObjectContainmentEList<JsonForm>(JsonForm.class, this, ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__FORMS);
    }
    return forms;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<JsonMultiLanguageEntry> getTitles()
  {
    if (titles == null)
    {
      titles = new EObjectContainmentEList<JsonMultiLanguageEntry>(JsonMultiLanguageEntry.class, this, ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__TITLES);
    }
    return titles;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<JsonMultiLanguageEntry> getDescriptions()
  {
    if (descriptions == null)
    {
      descriptions = new EObjectContainmentEList<JsonMultiLanguageEntry>(JsonMultiLanguageEntry.class, this, ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__DESCRIPTIONS);
    }
    return descriptions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<JsonDataSchema> getUriVariable()
  {
    if (uriVariable == null)
    {
      uriVariable = new EObjectContainmentEList<JsonDataSchema>(JsonDataSchema.class, this, ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__URI_VARIABLE);
    }
    return uriVariable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__DATA:
        return basicSetData(null, msgs);
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__SUBSCRIPTION:
        return basicSetSubscription(null, msgs);
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__CANCELLATION:
        return basicSetCancellation(null, msgs);
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__FORMS:
        return ((InternalEList<?>)getForms()).basicRemove(otherEnd, msgs);
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__TITLES:
        return ((InternalEList<?>)getTitles()).basicRemove(otherEnd, msgs);
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__DESCRIPTIONS:
        return ((InternalEList<?>)getDescriptions()).basicRemove(otherEnd, msgs);
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__URI_VARIABLE:
        return ((InternalEList<?>)getUriVariable()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__ID:
        return getId();
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__DATA:
        return getData();
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__SUBSCRIPTION:
        return getSubscription();
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__CANCELLATION:
        return getCancellation();
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__LD_TYPE:
        return getLd_type();
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__TITLE:
        return getTitle();
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__DESCRIPTION:
        return getDescription();
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__FORMS:
        return getForms();
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__TITLES:
        return getTitles();
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__DESCRIPTIONS:
        return getDescriptions();
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__URI_VARIABLE:
        return getUriVariable();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__ID:
        setId((String)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__DATA:
        setData((JsonDataSchema)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__SUBSCRIPTION:
        setSubscription((JsonDataSchema)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__CANCELLATION:
        setCancellation((JsonDataSchema)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__LD_TYPE:
        getLd_type().clear();
        getLd_type().addAll((Collection<? extends String>)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__TITLE:
        setTitle((String)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__DESCRIPTION:
        setDescription((String)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__FORMS:
        getForms().clear();
        getForms().addAll((Collection<? extends JsonForm>)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__TITLES:
        getTitles().clear();
        getTitles().addAll((Collection<? extends JsonMultiLanguageEntry>)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__DESCRIPTIONS:
        getDescriptions().clear();
        getDescriptions().addAll((Collection<? extends JsonMultiLanguageEntry>)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__URI_VARIABLE:
        getUriVariable().clear();
        getUriVariable().addAll((Collection<? extends JsonDataSchema>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__ID:
        setId(ID_EDEFAULT);
        return;
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__DATA:
        setData((JsonDataSchema)null);
        return;
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__SUBSCRIPTION:
        setSubscription((JsonDataSchema)null);
        return;
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__CANCELLATION:
        setCancellation((JsonDataSchema)null);
        return;
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__LD_TYPE:
        getLd_type().clear();
        return;
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__TITLE:
        setTitle(TITLE_EDEFAULT);
        return;
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__DESCRIPTION:
        setDescription(DESCRIPTION_EDEFAULT);
        return;
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__FORMS:
        getForms().clear();
        return;
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__TITLES:
        getTitles().clear();
        return;
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__DESCRIPTIONS:
        getDescriptions().clear();
        return;
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__URI_VARIABLE:
        getUriVariable().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__ID:
        return ID_EDEFAULT == null ? id != null : !ID_EDEFAULT.equals(id);
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__DATA:
        return data != null;
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__SUBSCRIPTION:
        return subscription != null;
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__CANCELLATION:
        return cancellation != null;
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__LD_TYPE:
        return ld_type != null && !ld_type.isEmpty();
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__TITLE:
        return TITLE_EDEFAULT == null ? title != null : !TITLE_EDEFAULT.equals(title);
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__DESCRIPTION:
        return DESCRIPTION_EDEFAULT == null ? description != null : !DESCRIPTION_EDEFAULT.equals(description);
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__FORMS:
        return forms != null && !forms.isEmpty();
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__TITLES:
        return titles != null && !titles.isEmpty();
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__DESCRIPTIONS:
        return descriptions != null && !descriptions.isEmpty();
      case ThingDescriptionJsonPackage.JSON_EVENT_AFFORDANCE__URI_VARIABLE:
        return uriVariable != null && !uriVariable.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (id: ");
    result.append(id);
    result.append(", ld_type: ");
    result.append(ld_type);
    result.append(", title: ");
    result.append(title);
    result.append(", description: ");
    result.append(description);
    result.append(')');
    return result.toString();
  }

} //JsonEventAffordanceImpl
