/**
 * generated by Xtext 2.17.0
 */
package edu.uoc.som.wot.td.json.thingDescriptionJson.impl;

import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonBoolean;
import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema;
import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonMultiLanguageEntry;
import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonType;
import edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Json Data Schema</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonDataSchemaImpl#getLd_type <em>Ld type</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonDataSchemaImpl#getTitle <em>Title</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonDataSchemaImpl#getDescription <em>Description</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonDataSchemaImpl#getType <em>Type</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonDataSchemaImpl#getConst <em>Const</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonDataSchemaImpl#getUnit <em>Unit</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonDataSchemaImpl#getEnum <em>Enum</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonDataSchemaImpl#getReadOnly <em>Read Only</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonDataSchemaImpl#getWriteOnly <em>Write Only</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonDataSchemaImpl#getFormat <em>Format</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonDataSchemaImpl#getOneOf <em>One Of</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonDataSchemaImpl#getTitles <em>Titles</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonDataSchemaImpl#getDescriptions <em>Descriptions</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonDataSchemaImpl#getMinItems <em>Min Items</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonDataSchemaImpl#getMaxItems <em>Max Items</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonDataSchemaImpl#getItems <em>Items</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonDataSchemaImpl#getRequired <em>Required</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonDataSchemaImpl#getProperties <em>Properties</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonDataSchemaImpl#getMinimum <em>Minimum</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonDataSchemaImpl#getMaximum <em>Maximum</em>}</li>
 * </ul>
 *
 * @generated
 */
public class JsonDataSchemaImpl extends MinimalEObjectImpl.Container implements JsonDataSchema
{
  /**
   * The cached value of the '{@link #getLd_type() <em>Ld type</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLd_type()
   * @generated
   * @ordered
   */
  protected EList<String> ld_type;

  /**
   * The default value of the '{@link #getTitle() <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitle()
   * @generated
   * @ordered
   */
  protected static final String TITLE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTitle() <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitle()
   * @generated
   * @ordered
   */
  protected String title = TITLE_EDEFAULT;

  /**
   * The default value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected static final String DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected String description = DESCRIPTION_EDEFAULT;

  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final JsonType TYPE_EDEFAULT = JsonType.STRING;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected JsonType type = TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getConst() <em>Const</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConst()
   * @generated
   * @ordered
   */
  protected static final String CONST_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getConst() <em>Const</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConst()
   * @generated
   * @ordered
   */
  protected String const_ = CONST_EDEFAULT;

  /**
   * The default value of the '{@link #getUnit() <em>Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnit()
   * @generated
   * @ordered
   */
  protected static final String UNIT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getUnit() <em>Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnit()
   * @generated
   * @ordered
   */
  protected String unit = UNIT_EDEFAULT;

  /**
   * The cached value of the '{@link #getEnum() <em>Enum</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnum()
   * @generated
   * @ordered
   */
  protected EList<String> enum_;

  /**
   * The default value of the '{@link #getReadOnly() <em>Read Only</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReadOnly()
   * @generated
   * @ordered
   */
  protected static final JsonBoolean READ_ONLY_EDEFAULT = JsonBoolean._FALSE;

  /**
   * The cached value of the '{@link #getReadOnly() <em>Read Only</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReadOnly()
   * @generated
   * @ordered
   */
  protected JsonBoolean readOnly = READ_ONLY_EDEFAULT;

  /**
   * The default value of the '{@link #getWriteOnly() <em>Write Only</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWriteOnly()
   * @generated
   * @ordered
   */
  protected static final JsonBoolean WRITE_ONLY_EDEFAULT = JsonBoolean._FALSE;

  /**
   * The cached value of the '{@link #getWriteOnly() <em>Write Only</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWriteOnly()
   * @generated
   * @ordered
   */
  protected JsonBoolean writeOnly = WRITE_ONLY_EDEFAULT;

  /**
   * The default value of the '{@link #getFormat() <em>Format</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFormat()
   * @generated
   * @ordered
   */
  protected static final String FORMAT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFormat() <em>Format</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFormat()
   * @generated
   * @ordered
   */
  protected String format = FORMAT_EDEFAULT;

  /**
   * The cached value of the '{@link #getOneOf() <em>One Of</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOneOf()
   * @generated
   * @ordered
   */
  protected EList<JsonDataSchema> oneOf;

  /**
   * The cached value of the '{@link #getTitles() <em>Titles</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitles()
   * @generated
   * @ordered
   */
  protected EList<JsonMultiLanguageEntry> titles;

  /**
   * The cached value of the '{@link #getDescriptions() <em>Descriptions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescriptions()
   * @generated
   * @ordered
   */
  protected EList<JsonMultiLanguageEntry> descriptions;

  /**
   * The default value of the '{@link #getMinItems() <em>Min Items</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMinItems()
   * @generated
   * @ordered
   */
  protected static final int MIN_ITEMS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getMinItems() <em>Min Items</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMinItems()
   * @generated
   * @ordered
   */
  protected int minItems = MIN_ITEMS_EDEFAULT;

  /**
   * The default value of the '{@link #getMaxItems() <em>Max Items</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaxItems()
   * @generated
   * @ordered
   */
  protected static final int MAX_ITEMS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getMaxItems() <em>Max Items</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaxItems()
   * @generated
   * @ordered
   */
  protected int maxItems = MAX_ITEMS_EDEFAULT;

  /**
   * The cached value of the '{@link #getItems() <em>Items</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getItems()
   * @generated
   * @ordered
   */
  protected EList<JsonDataSchema> items;

  /**
   * The cached value of the '{@link #getRequired() <em>Required</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRequired()
   * @generated
   * @ordered
   */
  protected EList<String> required;

  /**
   * The cached value of the '{@link #getProperties() <em>Properties</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProperties()
   * @generated
   * @ordered
   */
  protected EList<JsonDataSchema> properties;

  /**
   * The default value of the '{@link #getMinimum() <em>Minimum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMinimum()
   * @generated
   * @ordered
   */
  protected static final int MINIMUM_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getMinimum() <em>Minimum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMinimum()
   * @generated
   * @ordered
   */
  protected int minimum = MINIMUM_EDEFAULT;

  /**
   * The default value of the '{@link #getMaximum() <em>Maximum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaximum()
   * @generated
   * @ordered
   */
  protected static final int MAXIMUM_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getMaximum() <em>Maximum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaximum()
   * @generated
   * @ordered
   */
  protected int maximum = MAXIMUM_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JsonDataSchemaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThingDescriptionJsonPackage.Literals.JSON_DATA_SCHEMA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getLd_type()
  {
    if (ld_type == null)
    {
      ld_type = new EDataTypeEList<String>(String.class, this, ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__LD_TYPE);
    }
    return ld_type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTitle()
  {
    return title;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTitle(String newTitle)
  {
    String oldTitle = title;
    title = newTitle;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__TITLE, oldTitle, title));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDescription()
  {
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDescription(String newDescription)
  {
    String oldDescription = description;
    description = newDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__DESCRIPTION, oldDescription, description));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JsonType getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(JsonType newType)
  {
    JsonType oldType = type;
    type = newType == null ? TYPE_EDEFAULT : newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getConst()
  {
    return const_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setConst(String newConst)
  {
    String oldConst = const_;
    const_ = newConst;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__CONST, oldConst, const_));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getUnit()
  {
    return unit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUnit(String newUnit)
  {
    String oldUnit = unit;
    unit = newUnit;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__UNIT, oldUnit, unit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getEnum()
  {
    if (enum_ == null)
    {
      enum_ = new EDataTypeEList<String>(String.class, this, ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__ENUM);
    }
    return enum_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JsonBoolean getReadOnly()
  {
    return readOnly;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setReadOnly(JsonBoolean newReadOnly)
  {
    JsonBoolean oldReadOnly = readOnly;
    readOnly = newReadOnly == null ? READ_ONLY_EDEFAULT : newReadOnly;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__READ_ONLY, oldReadOnly, readOnly));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JsonBoolean getWriteOnly()
  {
    return writeOnly;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWriteOnly(JsonBoolean newWriteOnly)
  {
    JsonBoolean oldWriteOnly = writeOnly;
    writeOnly = newWriteOnly == null ? WRITE_ONLY_EDEFAULT : newWriteOnly;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__WRITE_ONLY, oldWriteOnly, writeOnly));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getFormat()
  {
    return format;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFormat(String newFormat)
  {
    String oldFormat = format;
    format = newFormat;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__FORMAT, oldFormat, format));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<JsonDataSchema> getOneOf()
  {
    if (oneOf == null)
    {
      oneOf = new EObjectContainmentEList<JsonDataSchema>(JsonDataSchema.class, this, ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__ONE_OF);
    }
    return oneOf;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<JsonMultiLanguageEntry> getTitles()
  {
    if (titles == null)
    {
      titles = new EObjectContainmentEList<JsonMultiLanguageEntry>(JsonMultiLanguageEntry.class, this, ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__TITLES);
    }
    return titles;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<JsonMultiLanguageEntry> getDescriptions()
  {
    if (descriptions == null)
    {
      descriptions = new EObjectContainmentEList<JsonMultiLanguageEntry>(JsonMultiLanguageEntry.class, this, ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__DESCRIPTIONS);
    }
    return descriptions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getMinItems()
  {
    return minItems;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMinItems(int newMinItems)
  {
    int oldMinItems = minItems;
    minItems = newMinItems;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__MIN_ITEMS, oldMinItems, minItems));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getMaxItems()
  {
    return maxItems;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMaxItems(int newMaxItems)
  {
    int oldMaxItems = maxItems;
    maxItems = newMaxItems;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__MAX_ITEMS, oldMaxItems, maxItems));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<JsonDataSchema> getItems()
  {
    if (items == null)
    {
      items = new EObjectContainmentEList<JsonDataSchema>(JsonDataSchema.class, this, ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__ITEMS);
    }
    return items;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getRequired()
  {
    if (required == null)
    {
      required = new EDataTypeEList<String>(String.class, this, ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__REQUIRED);
    }
    return required;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<JsonDataSchema> getProperties()
  {
    if (properties == null)
    {
      properties = new EObjectContainmentEList<JsonDataSchema>(JsonDataSchema.class, this, ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__PROPERTIES);
    }
    return properties;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getMinimum()
  {
    return minimum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMinimum(int newMinimum)
  {
    int oldMinimum = minimum;
    minimum = newMinimum;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__MINIMUM, oldMinimum, minimum));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getMaximum()
  {
    return maximum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMaximum(int newMaximum)
  {
    int oldMaximum = maximum;
    maximum = newMaximum;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__MAXIMUM, oldMaximum, maximum));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__ONE_OF:
        return ((InternalEList<?>)getOneOf()).basicRemove(otherEnd, msgs);
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__TITLES:
        return ((InternalEList<?>)getTitles()).basicRemove(otherEnd, msgs);
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__DESCRIPTIONS:
        return ((InternalEList<?>)getDescriptions()).basicRemove(otherEnd, msgs);
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__ITEMS:
        return ((InternalEList<?>)getItems()).basicRemove(otherEnd, msgs);
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__PROPERTIES:
        return ((InternalEList<?>)getProperties()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__LD_TYPE:
        return getLd_type();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__TITLE:
        return getTitle();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__DESCRIPTION:
        return getDescription();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__TYPE:
        return getType();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__CONST:
        return getConst();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__UNIT:
        return getUnit();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__ENUM:
        return getEnum();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__READ_ONLY:
        return getReadOnly();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__WRITE_ONLY:
        return getWriteOnly();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__FORMAT:
        return getFormat();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__ONE_OF:
        return getOneOf();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__TITLES:
        return getTitles();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__DESCRIPTIONS:
        return getDescriptions();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__MIN_ITEMS:
        return getMinItems();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__MAX_ITEMS:
        return getMaxItems();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__ITEMS:
        return getItems();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__REQUIRED:
        return getRequired();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__PROPERTIES:
        return getProperties();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__MINIMUM:
        return getMinimum();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__MAXIMUM:
        return getMaximum();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__LD_TYPE:
        getLd_type().clear();
        getLd_type().addAll((Collection<? extends String>)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__TITLE:
        setTitle((String)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__DESCRIPTION:
        setDescription((String)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__TYPE:
        setType((JsonType)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__CONST:
        setConst((String)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__UNIT:
        setUnit((String)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__ENUM:
        getEnum().clear();
        getEnum().addAll((Collection<? extends String>)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__READ_ONLY:
        setReadOnly((JsonBoolean)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__WRITE_ONLY:
        setWriteOnly((JsonBoolean)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__FORMAT:
        setFormat((String)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__ONE_OF:
        getOneOf().clear();
        getOneOf().addAll((Collection<? extends JsonDataSchema>)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__TITLES:
        getTitles().clear();
        getTitles().addAll((Collection<? extends JsonMultiLanguageEntry>)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__DESCRIPTIONS:
        getDescriptions().clear();
        getDescriptions().addAll((Collection<? extends JsonMultiLanguageEntry>)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__MIN_ITEMS:
        setMinItems((Integer)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__MAX_ITEMS:
        setMaxItems((Integer)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__ITEMS:
        getItems().clear();
        getItems().addAll((Collection<? extends JsonDataSchema>)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__REQUIRED:
        getRequired().clear();
        getRequired().addAll((Collection<? extends String>)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__PROPERTIES:
        getProperties().clear();
        getProperties().addAll((Collection<? extends JsonDataSchema>)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__MINIMUM:
        setMinimum((Integer)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__MAXIMUM:
        setMaximum((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__LD_TYPE:
        getLd_type().clear();
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__TITLE:
        setTitle(TITLE_EDEFAULT);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__DESCRIPTION:
        setDescription(DESCRIPTION_EDEFAULT);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__TYPE:
        setType(TYPE_EDEFAULT);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__CONST:
        setConst(CONST_EDEFAULT);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__UNIT:
        setUnit(UNIT_EDEFAULT);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__ENUM:
        getEnum().clear();
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__READ_ONLY:
        setReadOnly(READ_ONLY_EDEFAULT);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__WRITE_ONLY:
        setWriteOnly(WRITE_ONLY_EDEFAULT);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__FORMAT:
        setFormat(FORMAT_EDEFAULT);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__ONE_OF:
        getOneOf().clear();
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__TITLES:
        getTitles().clear();
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__DESCRIPTIONS:
        getDescriptions().clear();
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__MIN_ITEMS:
        setMinItems(MIN_ITEMS_EDEFAULT);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__MAX_ITEMS:
        setMaxItems(MAX_ITEMS_EDEFAULT);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__ITEMS:
        getItems().clear();
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__REQUIRED:
        getRequired().clear();
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__PROPERTIES:
        getProperties().clear();
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__MINIMUM:
        setMinimum(MINIMUM_EDEFAULT);
        return;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__MAXIMUM:
        setMaximum(MAXIMUM_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__LD_TYPE:
        return ld_type != null && !ld_type.isEmpty();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__TITLE:
        return TITLE_EDEFAULT == null ? title != null : !TITLE_EDEFAULT.equals(title);
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__DESCRIPTION:
        return DESCRIPTION_EDEFAULT == null ? description != null : !DESCRIPTION_EDEFAULT.equals(description);
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__TYPE:
        return type != TYPE_EDEFAULT;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__CONST:
        return CONST_EDEFAULT == null ? const_ != null : !CONST_EDEFAULT.equals(const_);
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__UNIT:
        return UNIT_EDEFAULT == null ? unit != null : !UNIT_EDEFAULT.equals(unit);
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__ENUM:
        return enum_ != null && !enum_.isEmpty();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__READ_ONLY:
        return readOnly != READ_ONLY_EDEFAULT;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__WRITE_ONLY:
        return writeOnly != WRITE_ONLY_EDEFAULT;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__FORMAT:
        return FORMAT_EDEFAULT == null ? format != null : !FORMAT_EDEFAULT.equals(format);
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__ONE_OF:
        return oneOf != null && !oneOf.isEmpty();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__TITLES:
        return titles != null && !titles.isEmpty();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__DESCRIPTIONS:
        return descriptions != null && !descriptions.isEmpty();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__MIN_ITEMS:
        return minItems != MIN_ITEMS_EDEFAULT;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__MAX_ITEMS:
        return maxItems != MAX_ITEMS_EDEFAULT;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__ITEMS:
        return items != null && !items.isEmpty();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__REQUIRED:
        return required != null && !required.isEmpty();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__PROPERTIES:
        return properties != null && !properties.isEmpty();
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__MINIMUM:
        return minimum != MINIMUM_EDEFAULT;
      case ThingDescriptionJsonPackage.JSON_DATA_SCHEMA__MAXIMUM:
        return maximum != MAXIMUM_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (ld_type: ");
    result.append(ld_type);
    result.append(", title: ");
    result.append(title);
    result.append(", description: ");
    result.append(description);
    result.append(", type: ");
    result.append(type);
    result.append(", const: ");
    result.append(const_);
    result.append(", unit: ");
    result.append(unit);
    result.append(", enum: ");
    result.append(enum_);
    result.append(", readOnly: ");
    result.append(readOnly);
    result.append(", writeOnly: ");
    result.append(writeOnly);
    result.append(", format: ");
    result.append(format);
    result.append(", minItems: ");
    result.append(minItems);
    result.append(", maxItems: ");
    result.append(maxItems);
    result.append(", required: ");
    result.append(required);
    result.append(", minimum: ");
    result.append(minimum);
    result.append(", maximum: ");
    result.append(maximum);
    result.append(')');
    return result.toString();
  }

} //JsonDataSchemaImpl
