/**
 * generated by Xtext 2.17.0
 */
package edu.uoc.som.wot.td.json.thingDescriptionJson.impl;

import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonActionAffordance;
import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonBoolean;
import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema;
import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonForm;
import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonMultiLanguageEntry;
import edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Json Action Affordance</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonActionAffordanceImpl#getId <em>Id</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonActionAffordanceImpl#getSafe <em>Safe</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonActionAffordanceImpl#getIdempotent <em>Idempotent</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonActionAffordanceImpl#getInput <em>Input</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonActionAffordanceImpl#getOutput <em>Output</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonActionAffordanceImpl#getLd_type <em>Ld type</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonActionAffordanceImpl#getTitle <em>Title</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonActionAffordanceImpl#getDescription <em>Description</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonActionAffordanceImpl#getForms <em>Forms</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonActionAffordanceImpl#getTitles <em>Titles</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonActionAffordanceImpl#getDescriptions <em>Descriptions</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonActionAffordanceImpl#getUriVariable <em>Uri Variable</em>}</li>
 * </ul>
 *
 * @generated
 */
public class JsonActionAffordanceImpl extends MinimalEObjectImpl.Container implements JsonActionAffordance
{
  /**
   * The default value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected static final String ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected String id = ID_EDEFAULT;

  /**
   * The default value of the '{@link #getSafe() <em>Safe</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSafe()
   * @generated
   * @ordered
   */
  protected static final JsonBoolean SAFE_EDEFAULT = JsonBoolean._FALSE;

  /**
   * The cached value of the '{@link #getSafe() <em>Safe</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSafe()
   * @generated
   * @ordered
   */
  protected JsonBoolean safe = SAFE_EDEFAULT;

  /**
   * The default value of the '{@link #getIdempotent() <em>Idempotent</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdempotent()
   * @generated
   * @ordered
   */
  protected static final JsonBoolean IDEMPOTENT_EDEFAULT = JsonBoolean._FALSE;

  /**
   * The cached value of the '{@link #getIdempotent() <em>Idempotent</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdempotent()
   * @generated
   * @ordered
   */
  protected JsonBoolean idempotent = IDEMPOTENT_EDEFAULT;

  /**
   * The cached value of the '{@link #getInput() <em>Input</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInput()
   * @generated
   * @ordered
   */
  protected JsonDataSchema input;

  /**
   * The cached value of the '{@link #getOutput() <em>Output</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOutput()
   * @generated
   * @ordered
   */
  protected JsonDataSchema output;

  /**
   * The cached value of the '{@link #getLd_type() <em>Ld type</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLd_type()
   * @generated
   * @ordered
   */
  protected EList<String> ld_type;

  /**
   * The default value of the '{@link #getTitle() <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitle()
   * @generated
   * @ordered
   */
  protected static final String TITLE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTitle() <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitle()
   * @generated
   * @ordered
   */
  protected String title = TITLE_EDEFAULT;

  /**
   * The default value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected static final String DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected String description = DESCRIPTION_EDEFAULT;

  /**
   * The cached value of the '{@link #getForms() <em>Forms</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getForms()
   * @generated
   * @ordered
   */
  protected EList<JsonForm> forms;

  /**
   * The cached value of the '{@link #getTitles() <em>Titles</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitles()
   * @generated
   * @ordered
   */
  protected EList<JsonMultiLanguageEntry> titles;

  /**
   * The cached value of the '{@link #getDescriptions() <em>Descriptions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescriptions()
   * @generated
   * @ordered
   */
  protected EList<JsonMultiLanguageEntry> descriptions;

  /**
   * The cached value of the '{@link #getUriVariable() <em>Uri Variable</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUriVariable()
   * @generated
   * @ordered
   */
  protected EList<JsonDataSchema> uriVariable;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JsonActionAffordanceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThingDescriptionJsonPackage.Literals.JSON_ACTION_AFFORDANCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getId()
  {
    return id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setId(String newId)
  {
    String oldId = id;
    id = newId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__ID, oldId, id));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JsonBoolean getSafe()
  {
    return safe;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSafe(JsonBoolean newSafe)
  {
    JsonBoolean oldSafe = safe;
    safe = newSafe == null ? SAFE_EDEFAULT : newSafe;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__SAFE, oldSafe, safe));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JsonBoolean getIdempotent()
  {
    return idempotent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIdempotent(JsonBoolean newIdempotent)
  {
    JsonBoolean oldIdempotent = idempotent;
    idempotent = newIdempotent == null ? IDEMPOTENT_EDEFAULT : newIdempotent;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__IDEMPOTENT, oldIdempotent, idempotent));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JsonDataSchema getInput()
  {
    return input;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInput(JsonDataSchema newInput, NotificationChain msgs)
  {
    JsonDataSchema oldInput = input;
    input = newInput;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__INPUT, oldInput, newInput);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInput(JsonDataSchema newInput)
  {
    if (newInput != input)
    {
      NotificationChain msgs = null;
      if (input != null)
        msgs = ((InternalEObject)input).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__INPUT, null, msgs);
      if (newInput != null)
        msgs = ((InternalEObject)newInput).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__INPUT, null, msgs);
      msgs = basicSetInput(newInput, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__INPUT, newInput, newInput));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JsonDataSchema getOutput()
  {
    return output;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOutput(JsonDataSchema newOutput, NotificationChain msgs)
  {
    JsonDataSchema oldOutput = output;
    output = newOutput;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__OUTPUT, oldOutput, newOutput);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOutput(JsonDataSchema newOutput)
  {
    if (newOutput != output)
    {
      NotificationChain msgs = null;
      if (output != null)
        msgs = ((InternalEObject)output).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__OUTPUT, null, msgs);
      if (newOutput != null)
        msgs = ((InternalEObject)newOutput).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__OUTPUT, null, msgs);
      msgs = basicSetOutput(newOutput, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__OUTPUT, newOutput, newOutput));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getLd_type()
  {
    if (ld_type == null)
    {
      ld_type = new EDataTypeEList<String>(String.class, this, ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__LD_TYPE);
    }
    return ld_type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTitle()
  {
    return title;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTitle(String newTitle)
  {
    String oldTitle = title;
    title = newTitle;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__TITLE, oldTitle, title));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDescription()
  {
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDescription(String newDescription)
  {
    String oldDescription = description;
    description = newDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__DESCRIPTION, oldDescription, description));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<JsonForm> getForms()
  {
    if (forms == null)
    {
      forms = new EObjectContainmentEList<JsonForm>(JsonForm.class, this, ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__FORMS);
    }
    return forms;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<JsonMultiLanguageEntry> getTitles()
  {
    if (titles == null)
    {
      titles = new EObjectContainmentEList<JsonMultiLanguageEntry>(JsonMultiLanguageEntry.class, this, ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__TITLES);
    }
    return titles;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<JsonMultiLanguageEntry> getDescriptions()
  {
    if (descriptions == null)
    {
      descriptions = new EObjectContainmentEList<JsonMultiLanguageEntry>(JsonMultiLanguageEntry.class, this, ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__DESCRIPTIONS);
    }
    return descriptions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<JsonDataSchema> getUriVariable()
  {
    if (uriVariable == null)
    {
      uriVariable = new EObjectContainmentEList<JsonDataSchema>(JsonDataSchema.class, this, ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__URI_VARIABLE);
    }
    return uriVariable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__INPUT:
        return basicSetInput(null, msgs);
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__OUTPUT:
        return basicSetOutput(null, msgs);
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__FORMS:
        return ((InternalEList<?>)getForms()).basicRemove(otherEnd, msgs);
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__TITLES:
        return ((InternalEList<?>)getTitles()).basicRemove(otherEnd, msgs);
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__DESCRIPTIONS:
        return ((InternalEList<?>)getDescriptions()).basicRemove(otherEnd, msgs);
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__URI_VARIABLE:
        return ((InternalEList<?>)getUriVariable()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__ID:
        return getId();
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__SAFE:
        return getSafe();
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__IDEMPOTENT:
        return getIdempotent();
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__INPUT:
        return getInput();
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__OUTPUT:
        return getOutput();
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__LD_TYPE:
        return getLd_type();
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__TITLE:
        return getTitle();
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__DESCRIPTION:
        return getDescription();
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__FORMS:
        return getForms();
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__TITLES:
        return getTitles();
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__DESCRIPTIONS:
        return getDescriptions();
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__URI_VARIABLE:
        return getUriVariable();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__ID:
        setId((String)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__SAFE:
        setSafe((JsonBoolean)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__IDEMPOTENT:
        setIdempotent((JsonBoolean)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__INPUT:
        setInput((JsonDataSchema)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__OUTPUT:
        setOutput((JsonDataSchema)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__LD_TYPE:
        getLd_type().clear();
        getLd_type().addAll((Collection<? extends String>)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__TITLE:
        setTitle((String)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__DESCRIPTION:
        setDescription((String)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__FORMS:
        getForms().clear();
        getForms().addAll((Collection<? extends JsonForm>)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__TITLES:
        getTitles().clear();
        getTitles().addAll((Collection<? extends JsonMultiLanguageEntry>)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__DESCRIPTIONS:
        getDescriptions().clear();
        getDescriptions().addAll((Collection<? extends JsonMultiLanguageEntry>)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__URI_VARIABLE:
        getUriVariable().clear();
        getUriVariable().addAll((Collection<? extends JsonDataSchema>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__ID:
        setId(ID_EDEFAULT);
        return;
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__SAFE:
        setSafe(SAFE_EDEFAULT);
        return;
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__IDEMPOTENT:
        setIdempotent(IDEMPOTENT_EDEFAULT);
        return;
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__INPUT:
        setInput((JsonDataSchema)null);
        return;
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__OUTPUT:
        setOutput((JsonDataSchema)null);
        return;
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__LD_TYPE:
        getLd_type().clear();
        return;
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__TITLE:
        setTitle(TITLE_EDEFAULT);
        return;
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__DESCRIPTION:
        setDescription(DESCRIPTION_EDEFAULT);
        return;
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__FORMS:
        getForms().clear();
        return;
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__TITLES:
        getTitles().clear();
        return;
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__DESCRIPTIONS:
        getDescriptions().clear();
        return;
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__URI_VARIABLE:
        getUriVariable().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__ID:
        return ID_EDEFAULT == null ? id != null : !ID_EDEFAULT.equals(id);
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__SAFE:
        return safe != SAFE_EDEFAULT;
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__IDEMPOTENT:
        return idempotent != IDEMPOTENT_EDEFAULT;
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__INPUT:
        return input != null;
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__OUTPUT:
        return output != null;
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__LD_TYPE:
        return ld_type != null && !ld_type.isEmpty();
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__TITLE:
        return TITLE_EDEFAULT == null ? title != null : !TITLE_EDEFAULT.equals(title);
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__DESCRIPTION:
        return DESCRIPTION_EDEFAULT == null ? description != null : !DESCRIPTION_EDEFAULT.equals(description);
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__FORMS:
        return forms != null && !forms.isEmpty();
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__TITLES:
        return titles != null && !titles.isEmpty();
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__DESCRIPTIONS:
        return descriptions != null && !descriptions.isEmpty();
      case ThingDescriptionJsonPackage.JSON_ACTION_AFFORDANCE__URI_VARIABLE:
        return uriVariable != null && !uriVariable.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (id: ");
    result.append(id);
    result.append(", safe: ");
    result.append(safe);
    result.append(", idempotent: ");
    result.append(idempotent);
    result.append(", ld_type: ");
    result.append(ld_type);
    result.append(", title: ");
    result.append(title);
    result.append(", description: ");
    result.append(description);
    result.append(')');
    return result.toString();
  }

} //JsonActionAffordanceImpl
