/**
 * generated by Xtext 2.17.0
 */
package edu.uoc.som.wot.td.json.thingDescriptionJson.impl;

import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonLink;
import edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Json Link</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonLinkImpl#get_href <em>href</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonLinkImpl#getType <em>Type</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonLinkImpl#getRel <em>Rel</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.impl.JsonLinkImpl#getAnchor <em>Anchor</em>}</li>
 * </ul>
 *
 * @generated
 */
public class JsonLinkImpl extends MinimalEObjectImpl.Container implements JsonLink
{
  /**
   * The default value of the '{@link #get_href() <em>href</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #get_href()
   * @generated
   * @ordered
   */
  protected static final String _HREF_EDEFAULT = null;

  /**
   * The cached value of the '{@link #get_href() <em>href</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #get_href()
   * @generated
   * @ordered
   */
  protected String _href = _HREF_EDEFAULT;

  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final String TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected String type = TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getRel() <em>Rel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRel()
   * @generated
   * @ordered
   */
  protected static final String REL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRel() <em>Rel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRel()
   * @generated
   * @ordered
   */
  protected String rel = REL_EDEFAULT;

  /**
   * The default value of the '{@link #getAnchor() <em>Anchor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAnchor()
   * @generated
   * @ordered
   */
  protected static final String ANCHOR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAnchor() <em>Anchor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAnchor()
   * @generated
   * @ordered
   */
  protected String anchor = ANCHOR_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JsonLinkImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThingDescriptionJsonPackage.Literals.JSON_LINK;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String get_href()
  {
    return _href;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void set_href(String new_href)
  {
    String old_href = _href;
    _href = new_href;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_LINK__HREF, old_href, _href));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(String newType)
  {
    String oldType = type;
    type = newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_LINK__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRel()
  {
    return rel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRel(String newRel)
  {
    String oldRel = rel;
    rel = newRel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_LINK__REL, oldRel, rel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getAnchor()
  {
    return anchor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAnchor(String newAnchor)
  {
    String oldAnchor = anchor;
    anchor = newAnchor;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingDescriptionJsonPackage.JSON_LINK__ANCHOR, oldAnchor, anchor));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ThingDescriptionJsonPackage.JSON_LINK__HREF:
        return get_href();
      case ThingDescriptionJsonPackage.JSON_LINK__TYPE:
        return getType();
      case ThingDescriptionJsonPackage.JSON_LINK__REL:
        return getRel();
      case ThingDescriptionJsonPackage.JSON_LINK__ANCHOR:
        return getAnchor();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ThingDescriptionJsonPackage.JSON_LINK__HREF:
        set_href((String)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_LINK__TYPE:
        setType((String)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_LINK__REL:
        setRel((String)newValue);
        return;
      case ThingDescriptionJsonPackage.JSON_LINK__ANCHOR:
        setAnchor((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ThingDescriptionJsonPackage.JSON_LINK__HREF:
        set_href(_HREF_EDEFAULT);
        return;
      case ThingDescriptionJsonPackage.JSON_LINK__TYPE:
        setType(TYPE_EDEFAULT);
        return;
      case ThingDescriptionJsonPackage.JSON_LINK__REL:
        setRel(REL_EDEFAULT);
        return;
      case ThingDescriptionJsonPackage.JSON_LINK__ANCHOR:
        setAnchor(ANCHOR_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ThingDescriptionJsonPackage.JSON_LINK__HREF:
        return _HREF_EDEFAULT == null ? _href != null : !_HREF_EDEFAULT.equals(_href);
      case ThingDescriptionJsonPackage.JSON_LINK__TYPE:
        return TYPE_EDEFAULT == null ? type != null : !TYPE_EDEFAULT.equals(type);
      case ThingDescriptionJsonPackage.JSON_LINK__REL:
        return REL_EDEFAULT == null ? rel != null : !REL_EDEFAULT.equals(rel);
      case ThingDescriptionJsonPackage.JSON_LINK__ANCHOR:
        return ANCHOR_EDEFAULT == null ? anchor != null : !ANCHOR_EDEFAULT.equals(anchor);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (_href: ");
    result.append(_href);
    result.append(", type: ");
    result.append(type);
    result.append(", rel: ");
    result.append(rel);
    result.append(", anchor: ");
    result.append(anchor);
    result.append(')');
    return result.toString();
  }

} //JsonLinkImpl
