/**
 * generated by Xtext 2.17.0
 */
package edu.uoc.som.wot.td.json.thingDescriptionJson.impl;

import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonActionAffordance;
import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonBoolean;
import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema;
import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonEventAffordance;
import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonExpectedResponse;
import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonForm;
import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonLink;
import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonMultiLanguageEntry;
import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance;
import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonSecurityScheme;
import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonThing;
import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonType;
import edu.uoc.som.wot.td.json.thingDescriptionJson.JsonVersionInfo;
import edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonFactory;
import edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class ThingDescriptionJsonPackageImpl extends EPackageImpl implements ThingDescriptionJsonPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jsonThingEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jsonVersionInfoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jsonSecuritySchemeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jsonPropertyAffordanceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jsonActionAffordanceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jsonEventAffordanceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jsonDataSchemaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jsonLinkEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jsonFormEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jsonExpectedResponseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jsonMultiLanguageEntryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum jsonBooleanEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum jsonTypeEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private ThingDescriptionJsonPackageImpl()
  {
    super(eNS_URI, ThingDescriptionJsonFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link ThingDescriptionJsonPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static ThingDescriptionJsonPackage init()
  {
    if (isInited) return (ThingDescriptionJsonPackage)EPackage.Registry.INSTANCE.getEPackage(ThingDescriptionJsonPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredThingDescriptionJsonPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    ThingDescriptionJsonPackageImpl theThingDescriptionJsonPackage = registeredThingDescriptionJsonPackage instanceof ThingDescriptionJsonPackageImpl ? (ThingDescriptionJsonPackageImpl)registeredThingDescriptionJsonPackage : new ThingDescriptionJsonPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theThingDescriptionJsonPackage.createPackageContents();

    // Initialize created meta-data
    theThingDescriptionJsonPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theThingDescriptionJsonPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(ThingDescriptionJsonPackage.eNS_URI, theThingDescriptionJsonPackage);
    return theThingDescriptionJsonPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getJsonThing()
  {
    return jsonThingEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonThing_Ld_context()
  {
    return (EAttribute)jsonThingEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonThing_Ld_type()
  {
    return (EAttribute)jsonThingEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonThing_Id()
  {
    return (EAttribute)jsonThingEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonThing_Title()
  {
    return (EAttribute)jsonThingEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonThing_Description()
  {
    return (EAttribute)jsonThingEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonThing_Created()
  {
    return (EAttribute)jsonThingEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonThing_Modified()
  {
    return (EAttribute)jsonThingEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonThing_Support()
  {
    return (EAttribute)jsonThingEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonThing_Base()
  {
    return (EAttribute)jsonThingEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonThing_Security()
  {
    return (EAttribute)jsonThingEClass.getEStructuralFeatures().get(9);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonThing_Forms()
  {
    return (EReference)jsonThingEClass.getEStructuralFeatures().get(10);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonThing_Links()
  {
    return (EReference)jsonThingEClass.getEStructuralFeatures().get(11);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonThing_Titles()
  {
    return (EReference)jsonThingEClass.getEStructuralFeatures().get(12);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonThing_Descriptions()
  {
    return (EReference)jsonThingEClass.getEStructuralFeatures().get(13);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonThing_Version()
  {
    return (EReference)jsonThingEClass.getEStructuralFeatures().get(14);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonThing_Properties()
  {
    return (EReference)jsonThingEClass.getEStructuralFeatures().get(15);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonThing_Actions()
  {
    return (EReference)jsonThingEClass.getEStructuralFeatures().get(16);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonThing_Events()
  {
    return (EReference)jsonThingEClass.getEStructuralFeatures().get(17);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonThing_SecurityDefinitions()
  {
    return (EReference)jsonThingEClass.getEStructuralFeatures().get(18);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getJsonVersionInfo()
  {
    return jsonVersionInfoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonVersionInfo_Instance()
  {
    return (EAttribute)jsonVersionInfoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getJsonSecurityScheme()
  {
    return jsonSecuritySchemeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonSecurityScheme_Id()
  {
    return (EAttribute)jsonSecuritySchemeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getJsonPropertyAffordance()
  {
    return jsonPropertyAffordanceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonPropertyAffordance_Id()
  {
    return (EAttribute)jsonPropertyAffordanceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonPropertyAffordance_Observable()
  {
    return (EAttribute)jsonPropertyAffordanceEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonPropertyAffordance_Ld_type()
  {
    return (EAttribute)jsonPropertyAffordanceEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonPropertyAffordance_Title()
  {
    return (EAttribute)jsonPropertyAffordanceEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonPropertyAffordance_Description()
  {
    return (EAttribute)jsonPropertyAffordanceEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonPropertyAffordance_Titles()
  {
    return (EReference)jsonPropertyAffordanceEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonPropertyAffordance_Descriptions()
  {
    return (EReference)jsonPropertyAffordanceEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonPropertyAffordance_Forms()
  {
    return (EReference)jsonPropertyAffordanceEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonPropertyAffordance_UriVariable()
  {
    return (EReference)jsonPropertyAffordanceEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonPropertyAffordance_Type()
  {
    return (EAttribute)jsonPropertyAffordanceEClass.getEStructuralFeatures().get(9);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonPropertyAffordance_Const()
  {
    return (EAttribute)jsonPropertyAffordanceEClass.getEStructuralFeatures().get(10);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonPropertyAffordance_Unit()
  {
    return (EAttribute)jsonPropertyAffordanceEClass.getEStructuralFeatures().get(11);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonPropertyAffordance_Enum()
  {
    return (EAttribute)jsonPropertyAffordanceEClass.getEStructuralFeatures().get(12);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonPropertyAffordance_ReadOnly()
  {
    return (EAttribute)jsonPropertyAffordanceEClass.getEStructuralFeatures().get(13);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonPropertyAffordance_WriteOnly()
  {
    return (EAttribute)jsonPropertyAffordanceEClass.getEStructuralFeatures().get(14);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonPropertyAffordance_Format()
  {
    return (EAttribute)jsonPropertyAffordanceEClass.getEStructuralFeatures().get(15);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonPropertyAffordance_OneOf()
  {
    return (EReference)jsonPropertyAffordanceEClass.getEStructuralFeatures().get(16);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getJsonActionAffordance()
  {
    return jsonActionAffordanceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonActionAffordance_Id()
  {
    return (EAttribute)jsonActionAffordanceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonActionAffordance_Safe()
  {
    return (EAttribute)jsonActionAffordanceEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonActionAffordance_Idempotent()
  {
    return (EAttribute)jsonActionAffordanceEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonActionAffordance_Input()
  {
    return (EReference)jsonActionAffordanceEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonActionAffordance_Output()
  {
    return (EReference)jsonActionAffordanceEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonActionAffordance_Ld_type()
  {
    return (EAttribute)jsonActionAffordanceEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonActionAffordance_Title()
  {
    return (EAttribute)jsonActionAffordanceEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonActionAffordance_Description()
  {
    return (EAttribute)jsonActionAffordanceEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonActionAffordance_Forms()
  {
    return (EReference)jsonActionAffordanceEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonActionAffordance_Titles()
  {
    return (EReference)jsonActionAffordanceEClass.getEStructuralFeatures().get(9);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonActionAffordance_Descriptions()
  {
    return (EReference)jsonActionAffordanceEClass.getEStructuralFeatures().get(10);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonActionAffordance_UriVariable()
  {
    return (EReference)jsonActionAffordanceEClass.getEStructuralFeatures().get(11);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getJsonEventAffordance()
  {
    return jsonEventAffordanceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonEventAffordance_Id()
  {
    return (EAttribute)jsonEventAffordanceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonEventAffordance_Data()
  {
    return (EReference)jsonEventAffordanceEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonEventAffordance_Subscription()
  {
    return (EReference)jsonEventAffordanceEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonEventAffordance_Cancellation()
  {
    return (EReference)jsonEventAffordanceEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonEventAffordance_Ld_type()
  {
    return (EAttribute)jsonEventAffordanceEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonEventAffordance_Title()
  {
    return (EAttribute)jsonEventAffordanceEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonEventAffordance_Description()
  {
    return (EAttribute)jsonEventAffordanceEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonEventAffordance_Forms()
  {
    return (EReference)jsonEventAffordanceEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonEventAffordance_Titles()
  {
    return (EReference)jsonEventAffordanceEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonEventAffordance_Descriptions()
  {
    return (EReference)jsonEventAffordanceEClass.getEStructuralFeatures().get(9);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonEventAffordance_UriVariable()
  {
    return (EReference)jsonEventAffordanceEClass.getEStructuralFeatures().get(10);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getJsonDataSchema()
  {
    return jsonDataSchemaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonDataSchema_Ld_type()
  {
    return (EAttribute)jsonDataSchemaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonDataSchema_Title()
  {
    return (EAttribute)jsonDataSchemaEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonDataSchema_Description()
  {
    return (EAttribute)jsonDataSchemaEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonDataSchema_Type()
  {
    return (EAttribute)jsonDataSchemaEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonDataSchema_Const()
  {
    return (EAttribute)jsonDataSchemaEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonDataSchema_Unit()
  {
    return (EAttribute)jsonDataSchemaEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonDataSchema_Enum()
  {
    return (EAttribute)jsonDataSchemaEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonDataSchema_ReadOnly()
  {
    return (EAttribute)jsonDataSchemaEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonDataSchema_WriteOnly()
  {
    return (EAttribute)jsonDataSchemaEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonDataSchema_Format()
  {
    return (EAttribute)jsonDataSchemaEClass.getEStructuralFeatures().get(9);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonDataSchema_OneOf()
  {
    return (EReference)jsonDataSchemaEClass.getEStructuralFeatures().get(10);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonDataSchema_Titles()
  {
    return (EReference)jsonDataSchemaEClass.getEStructuralFeatures().get(11);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonDataSchema_Descriptions()
  {
    return (EReference)jsonDataSchemaEClass.getEStructuralFeatures().get(12);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonDataSchema_MinItems()
  {
    return (EAttribute)jsonDataSchemaEClass.getEStructuralFeatures().get(13);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonDataSchema_MaxItems()
  {
    return (EAttribute)jsonDataSchemaEClass.getEStructuralFeatures().get(14);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonDataSchema_Items()
  {
    return (EReference)jsonDataSchemaEClass.getEStructuralFeatures().get(15);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonDataSchema_Required()
  {
    return (EAttribute)jsonDataSchemaEClass.getEStructuralFeatures().get(16);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonDataSchema_Properties()
  {
    return (EReference)jsonDataSchemaEClass.getEStructuralFeatures().get(17);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonDataSchema_Minimum()
  {
    return (EAttribute)jsonDataSchemaEClass.getEStructuralFeatures().get(18);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonDataSchema_Maximum()
  {
    return (EAttribute)jsonDataSchemaEClass.getEStructuralFeatures().get(19);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getJsonLink()
  {
    return jsonLinkEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonLink__href()
  {
    return (EAttribute)jsonLinkEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonLink_Type()
  {
    return (EAttribute)jsonLinkEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonLink_Rel()
  {
    return (EAttribute)jsonLinkEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonLink_Anchor()
  {
    return (EAttribute)jsonLinkEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getJsonForm()
  {
    return jsonFormEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonForm_Ld_type()
  {
    return (EAttribute)jsonFormEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonForm_Op()
  {
    return (EAttribute)jsonFormEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonForm__href()
  {
    return (EAttribute)jsonFormEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonForm_ContentType()
  {
    return (EAttribute)jsonFormEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonForm_ContentCoding()
  {
    return (EAttribute)jsonFormEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonForm_Subprotocol()
  {
    return (EAttribute)jsonFormEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonForm_Security()
  {
    return (EAttribute)jsonFormEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonForm_Scopes()
  {
    return (EAttribute)jsonFormEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJsonForm_Response()
  {
    return (EReference)jsonFormEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getJsonExpectedResponse()
  {
    return jsonExpectedResponseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonExpectedResponse_ContentType()
  {
    return (EAttribute)jsonExpectedResponseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getJsonMultiLanguageEntry()
  {
    return jsonMultiLanguageEntryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonMultiLanguageEntry_Language()
  {
    return (EAttribute)jsonMultiLanguageEntryEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJsonMultiLanguageEntry_Content()
  {
    return (EAttribute)jsonMultiLanguageEntryEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getJsonBoolean()
  {
    return jsonBooleanEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getJsonType()
  {
    return jsonTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ThingDescriptionJsonFactory getThingDescriptionJsonFactory()
  {
    return (ThingDescriptionJsonFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    jsonThingEClass = createEClass(JSON_THING);
    createEAttribute(jsonThingEClass, JSON_THING__LD_CONTEXT);
    createEAttribute(jsonThingEClass, JSON_THING__LD_TYPE);
    createEAttribute(jsonThingEClass, JSON_THING__ID);
    createEAttribute(jsonThingEClass, JSON_THING__TITLE);
    createEAttribute(jsonThingEClass, JSON_THING__DESCRIPTION);
    createEAttribute(jsonThingEClass, JSON_THING__CREATED);
    createEAttribute(jsonThingEClass, JSON_THING__MODIFIED);
    createEAttribute(jsonThingEClass, JSON_THING__SUPPORT);
    createEAttribute(jsonThingEClass, JSON_THING__BASE);
    createEAttribute(jsonThingEClass, JSON_THING__SECURITY);
    createEReference(jsonThingEClass, JSON_THING__FORMS);
    createEReference(jsonThingEClass, JSON_THING__LINKS);
    createEReference(jsonThingEClass, JSON_THING__TITLES);
    createEReference(jsonThingEClass, JSON_THING__DESCRIPTIONS);
    createEReference(jsonThingEClass, JSON_THING__VERSION);
    createEReference(jsonThingEClass, JSON_THING__PROPERTIES);
    createEReference(jsonThingEClass, JSON_THING__ACTIONS);
    createEReference(jsonThingEClass, JSON_THING__EVENTS);
    createEReference(jsonThingEClass, JSON_THING__SECURITY_DEFINITIONS);

    jsonVersionInfoEClass = createEClass(JSON_VERSION_INFO);
    createEAttribute(jsonVersionInfoEClass, JSON_VERSION_INFO__INSTANCE);

    jsonSecuritySchemeEClass = createEClass(JSON_SECURITY_SCHEME);
    createEAttribute(jsonSecuritySchemeEClass, JSON_SECURITY_SCHEME__ID);

    jsonPropertyAffordanceEClass = createEClass(JSON_PROPERTY_AFFORDANCE);
    createEAttribute(jsonPropertyAffordanceEClass, JSON_PROPERTY_AFFORDANCE__ID);
    createEAttribute(jsonPropertyAffordanceEClass, JSON_PROPERTY_AFFORDANCE__OBSERVABLE);
    createEAttribute(jsonPropertyAffordanceEClass, JSON_PROPERTY_AFFORDANCE__LD_TYPE);
    createEAttribute(jsonPropertyAffordanceEClass, JSON_PROPERTY_AFFORDANCE__TITLE);
    createEAttribute(jsonPropertyAffordanceEClass, JSON_PROPERTY_AFFORDANCE__DESCRIPTION);
    createEReference(jsonPropertyAffordanceEClass, JSON_PROPERTY_AFFORDANCE__TITLES);
    createEReference(jsonPropertyAffordanceEClass, JSON_PROPERTY_AFFORDANCE__DESCRIPTIONS);
    createEReference(jsonPropertyAffordanceEClass, JSON_PROPERTY_AFFORDANCE__FORMS);
    createEReference(jsonPropertyAffordanceEClass, JSON_PROPERTY_AFFORDANCE__URI_VARIABLE);
    createEAttribute(jsonPropertyAffordanceEClass, JSON_PROPERTY_AFFORDANCE__TYPE);
    createEAttribute(jsonPropertyAffordanceEClass, JSON_PROPERTY_AFFORDANCE__CONST);
    createEAttribute(jsonPropertyAffordanceEClass, JSON_PROPERTY_AFFORDANCE__UNIT);
    createEAttribute(jsonPropertyAffordanceEClass, JSON_PROPERTY_AFFORDANCE__ENUM);
    createEAttribute(jsonPropertyAffordanceEClass, JSON_PROPERTY_AFFORDANCE__READ_ONLY);
    createEAttribute(jsonPropertyAffordanceEClass, JSON_PROPERTY_AFFORDANCE__WRITE_ONLY);
    createEAttribute(jsonPropertyAffordanceEClass, JSON_PROPERTY_AFFORDANCE__FORMAT);
    createEReference(jsonPropertyAffordanceEClass, JSON_PROPERTY_AFFORDANCE__ONE_OF);

    jsonActionAffordanceEClass = createEClass(JSON_ACTION_AFFORDANCE);
    createEAttribute(jsonActionAffordanceEClass, JSON_ACTION_AFFORDANCE__ID);
    createEAttribute(jsonActionAffordanceEClass, JSON_ACTION_AFFORDANCE__SAFE);
    createEAttribute(jsonActionAffordanceEClass, JSON_ACTION_AFFORDANCE__IDEMPOTENT);
    createEReference(jsonActionAffordanceEClass, JSON_ACTION_AFFORDANCE__INPUT);
    createEReference(jsonActionAffordanceEClass, JSON_ACTION_AFFORDANCE__OUTPUT);
    createEAttribute(jsonActionAffordanceEClass, JSON_ACTION_AFFORDANCE__LD_TYPE);
    createEAttribute(jsonActionAffordanceEClass, JSON_ACTION_AFFORDANCE__TITLE);
    createEAttribute(jsonActionAffordanceEClass, JSON_ACTION_AFFORDANCE__DESCRIPTION);
    createEReference(jsonActionAffordanceEClass, JSON_ACTION_AFFORDANCE__FORMS);
    createEReference(jsonActionAffordanceEClass, JSON_ACTION_AFFORDANCE__TITLES);
    createEReference(jsonActionAffordanceEClass, JSON_ACTION_AFFORDANCE__DESCRIPTIONS);
    createEReference(jsonActionAffordanceEClass, JSON_ACTION_AFFORDANCE__URI_VARIABLE);

    jsonEventAffordanceEClass = createEClass(JSON_EVENT_AFFORDANCE);
    createEAttribute(jsonEventAffordanceEClass, JSON_EVENT_AFFORDANCE__ID);
    createEReference(jsonEventAffordanceEClass, JSON_EVENT_AFFORDANCE__DATA);
    createEReference(jsonEventAffordanceEClass, JSON_EVENT_AFFORDANCE__SUBSCRIPTION);
    createEReference(jsonEventAffordanceEClass, JSON_EVENT_AFFORDANCE__CANCELLATION);
    createEAttribute(jsonEventAffordanceEClass, JSON_EVENT_AFFORDANCE__LD_TYPE);
    createEAttribute(jsonEventAffordanceEClass, JSON_EVENT_AFFORDANCE__TITLE);
    createEAttribute(jsonEventAffordanceEClass, JSON_EVENT_AFFORDANCE__DESCRIPTION);
    createEReference(jsonEventAffordanceEClass, JSON_EVENT_AFFORDANCE__FORMS);
    createEReference(jsonEventAffordanceEClass, JSON_EVENT_AFFORDANCE__TITLES);
    createEReference(jsonEventAffordanceEClass, JSON_EVENT_AFFORDANCE__DESCRIPTIONS);
    createEReference(jsonEventAffordanceEClass, JSON_EVENT_AFFORDANCE__URI_VARIABLE);

    jsonDataSchemaEClass = createEClass(JSON_DATA_SCHEMA);
    createEAttribute(jsonDataSchemaEClass, JSON_DATA_SCHEMA__LD_TYPE);
    createEAttribute(jsonDataSchemaEClass, JSON_DATA_SCHEMA__TITLE);
    createEAttribute(jsonDataSchemaEClass, JSON_DATA_SCHEMA__DESCRIPTION);
    createEAttribute(jsonDataSchemaEClass, JSON_DATA_SCHEMA__TYPE);
    createEAttribute(jsonDataSchemaEClass, JSON_DATA_SCHEMA__CONST);
    createEAttribute(jsonDataSchemaEClass, JSON_DATA_SCHEMA__UNIT);
    createEAttribute(jsonDataSchemaEClass, JSON_DATA_SCHEMA__ENUM);
    createEAttribute(jsonDataSchemaEClass, JSON_DATA_SCHEMA__READ_ONLY);
    createEAttribute(jsonDataSchemaEClass, JSON_DATA_SCHEMA__WRITE_ONLY);
    createEAttribute(jsonDataSchemaEClass, JSON_DATA_SCHEMA__FORMAT);
    createEReference(jsonDataSchemaEClass, JSON_DATA_SCHEMA__ONE_OF);
    createEReference(jsonDataSchemaEClass, JSON_DATA_SCHEMA__TITLES);
    createEReference(jsonDataSchemaEClass, JSON_DATA_SCHEMA__DESCRIPTIONS);
    createEAttribute(jsonDataSchemaEClass, JSON_DATA_SCHEMA__MIN_ITEMS);
    createEAttribute(jsonDataSchemaEClass, JSON_DATA_SCHEMA__MAX_ITEMS);
    createEReference(jsonDataSchemaEClass, JSON_DATA_SCHEMA__ITEMS);
    createEAttribute(jsonDataSchemaEClass, JSON_DATA_SCHEMA__REQUIRED);
    createEReference(jsonDataSchemaEClass, JSON_DATA_SCHEMA__PROPERTIES);
    createEAttribute(jsonDataSchemaEClass, JSON_DATA_SCHEMA__MINIMUM);
    createEAttribute(jsonDataSchemaEClass, JSON_DATA_SCHEMA__MAXIMUM);

    jsonLinkEClass = createEClass(JSON_LINK);
    createEAttribute(jsonLinkEClass, JSON_LINK__HREF);
    createEAttribute(jsonLinkEClass, JSON_LINK__TYPE);
    createEAttribute(jsonLinkEClass, JSON_LINK__REL);
    createEAttribute(jsonLinkEClass, JSON_LINK__ANCHOR);

    jsonFormEClass = createEClass(JSON_FORM);
    createEAttribute(jsonFormEClass, JSON_FORM__LD_TYPE);
    createEAttribute(jsonFormEClass, JSON_FORM__OP);
    createEAttribute(jsonFormEClass, JSON_FORM__HREF);
    createEAttribute(jsonFormEClass, JSON_FORM__CONTENT_TYPE);
    createEAttribute(jsonFormEClass, JSON_FORM__CONTENT_CODING);
    createEAttribute(jsonFormEClass, JSON_FORM__SUBPROTOCOL);
    createEAttribute(jsonFormEClass, JSON_FORM__SECURITY);
    createEAttribute(jsonFormEClass, JSON_FORM__SCOPES);
    createEReference(jsonFormEClass, JSON_FORM__RESPONSE);

    jsonExpectedResponseEClass = createEClass(JSON_EXPECTED_RESPONSE);
    createEAttribute(jsonExpectedResponseEClass, JSON_EXPECTED_RESPONSE__CONTENT_TYPE);

    jsonMultiLanguageEntryEClass = createEClass(JSON_MULTI_LANGUAGE_ENTRY);
    createEAttribute(jsonMultiLanguageEntryEClass, JSON_MULTI_LANGUAGE_ENTRY__LANGUAGE);
    createEAttribute(jsonMultiLanguageEntryEClass, JSON_MULTI_LANGUAGE_ENTRY__CONTENT);

    // Create enums
    jsonBooleanEEnum = createEEnum(JSON_BOOLEAN);
    jsonTypeEEnum = createEEnum(JSON_TYPE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes

    // Initialize classes and features; add operations and parameters
    initEClass(jsonThingEClass, JsonThing.class, "JsonThing", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJsonThing_Ld_context(), ecorePackage.getEString(), "ld_context", null, 0, -1, JsonThing.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonThing_Ld_type(), ecorePackage.getEString(), "ld_type", null, 0, -1, JsonThing.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonThing_Id(), ecorePackage.getEString(), "id", null, 0, 1, JsonThing.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonThing_Title(), ecorePackage.getEString(), "title", null, 0, 1, JsonThing.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonThing_Description(), ecorePackage.getEString(), "description", null, 0, 1, JsonThing.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonThing_Created(), ecorePackage.getEString(), "created", null, 0, 1, JsonThing.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonThing_Modified(), ecorePackage.getEString(), "modified", null, 0, 1, JsonThing.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonThing_Support(), ecorePackage.getEString(), "support", null, 0, 1, JsonThing.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonThing_Base(), ecorePackage.getEString(), "base", null, 0, 1, JsonThing.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonThing_Security(), ecorePackage.getEString(), "security", null, 0, -1, JsonThing.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonThing_Forms(), this.getJsonForm(), null, "forms", null, 0, -1, JsonThing.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonThing_Links(), this.getJsonLink(), null, "links", null, 0, -1, JsonThing.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonThing_Titles(), this.getJsonMultiLanguageEntry(), null, "titles", null, 0, -1, JsonThing.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonThing_Descriptions(), this.getJsonMultiLanguageEntry(), null, "descriptions", null, 0, -1, JsonThing.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonThing_Version(), this.getJsonVersionInfo(), null, "version", null, 0, 1, JsonThing.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonThing_Properties(), this.getJsonPropertyAffordance(), null, "properties", null, 0, -1, JsonThing.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonThing_Actions(), this.getJsonActionAffordance(), null, "actions", null, 0, -1, JsonThing.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonThing_Events(), this.getJsonEventAffordance(), null, "events", null, 0, -1, JsonThing.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonThing_SecurityDefinitions(), this.getJsonSecurityScheme(), null, "securityDefinitions", null, 0, -1, JsonThing.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jsonVersionInfoEClass, JsonVersionInfo.class, "JsonVersionInfo", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJsonVersionInfo_Instance(), ecorePackage.getEString(), "instance", null, 0, 1, JsonVersionInfo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jsonSecuritySchemeEClass, JsonSecurityScheme.class, "JsonSecurityScheme", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJsonSecurityScheme_Id(), ecorePackage.getEString(), "id", null, 0, 1, JsonSecurityScheme.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jsonPropertyAffordanceEClass, JsonPropertyAffordance.class, "JsonPropertyAffordance", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJsonPropertyAffordance_Id(), ecorePackage.getEString(), "id", null, 0, 1, JsonPropertyAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonPropertyAffordance_Observable(), this.getJsonBoolean(), "observable", null, 0, 1, JsonPropertyAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonPropertyAffordance_Ld_type(), ecorePackage.getEString(), "ld_type", null, 0, -1, JsonPropertyAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonPropertyAffordance_Title(), ecorePackage.getEString(), "title", null, 0, 1, JsonPropertyAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonPropertyAffordance_Description(), ecorePackage.getEString(), "description", null, 0, 1, JsonPropertyAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonPropertyAffordance_Titles(), this.getJsonMultiLanguageEntry(), null, "titles", null, 0, -1, JsonPropertyAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonPropertyAffordance_Descriptions(), this.getJsonMultiLanguageEntry(), null, "descriptions", null, 0, -1, JsonPropertyAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonPropertyAffordance_Forms(), this.getJsonForm(), null, "forms", null, 0, -1, JsonPropertyAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonPropertyAffordance_UriVariable(), this.getJsonDataSchema(), null, "uriVariable", null, 0, -1, JsonPropertyAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonPropertyAffordance_Type(), this.getJsonType(), "type", null, 0, 1, JsonPropertyAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonPropertyAffordance_Const(), ecorePackage.getEString(), "const", null, 0, 1, JsonPropertyAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonPropertyAffordance_Unit(), ecorePackage.getEString(), "unit", null, 0, 1, JsonPropertyAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonPropertyAffordance_Enum(), ecorePackage.getEString(), "enum", null, 0, -1, JsonPropertyAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonPropertyAffordance_ReadOnly(), this.getJsonBoolean(), "readOnly", null, 0, 1, JsonPropertyAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonPropertyAffordance_WriteOnly(), this.getJsonBoolean(), "writeOnly", null, 0, 1, JsonPropertyAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonPropertyAffordance_Format(), ecorePackage.getEString(), "format", null, 0, 1, JsonPropertyAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonPropertyAffordance_OneOf(), this.getJsonDataSchema(), null, "oneOf", null, 0, -1, JsonPropertyAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jsonActionAffordanceEClass, JsonActionAffordance.class, "JsonActionAffordance", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJsonActionAffordance_Id(), ecorePackage.getEString(), "id", null, 0, 1, JsonActionAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonActionAffordance_Safe(), this.getJsonBoolean(), "safe", null, 0, 1, JsonActionAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonActionAffordance_Idempotent(), this.getJsonBoolean(), "idempotent", null, 0, 1, JsonActionAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonActionAffordance_Input(), this.getJsonDataSchema(), null, "input", null, 0, 1, JsonActionAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonActionAffordance_Output(), this.getJsonDataSchema(), null, "output", null, 0, 1, JsonActionAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonActionAffordance_Ld_type(), ecorePackage.getEString(), "ld_type", null, 0, -1, JsonActionAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonActionAffordance_Title(), ecorePackage.getEString(), "title", null, 0, 1, JsonActionAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonActionAffordance_Description(), ecorePackage.getEString(), "description", null, 0, 1, JsonActionAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonActionAffordance_Forms(), this.getJsonForm(), null, "forms", null, 0, -1, JsonActionAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonActionAffordance_Titles(), this.getJsonMultiLanguageEntry(), null, "titles", null, 0, -1, JsonActionAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonActionAffordance_Descriptions(), this.getJsonMultiLanguageEntry(), null, "descriptions", null, 0, -1, JsonActionAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonActionAffordance_UriVariable(), this.getJsonDataSchema(), null, "uriVariable", null, 0, -1, JsonActionAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jsonEventAffordanceEClass, JsonEventAffordance.class, "JsonEventAffordance", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJsonEventAffordance_Id(), ecorePackage.getEString(), "id", null, 0, 1, JsonEventAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonEventAffordance_Data(), this.getJsonDataSchema(), null, "data", null, 0, 1, JsonEventAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonEventAffordance_Subscription(), this.getJsonDataSchema(), null, "subscription", null, 0, 1, JsonEventAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonEventAffordance_Cancellation(), this.getJsonDataSchema(), null, "cancellation", null, 0, 1, JsonEventAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonEventAffordance_Ld_type(), ecorePackage.getEString(), "ld_type", null, 0, -1, JsonEventAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonEventAffordance_Title(), ecorePackage.getEString(), "title", null, 0, 1, JsonEventAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonEventAffordance_Description(), ecorePackage.getEString(), "description", null, 0, 1, JsonEventAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonEventAffordance_Forms(), this.getJsonForm(), null, "forms", null, 0, -1, JsonEventAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonEventAffordance_Titles(), this.getJsonMultiLanguageEntry(), null, "titles", null, 0, -1, JsonEventAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonEventAffordance_Descriptions(), this.getJsonMultiLanguageEntry(), null, "descriptions", null, 0, -1, JsonEventAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonEventAffordance_UriVariable(), this.getJsonDataSchema(), null, "uriVariable", null, 0, -1, JsonEventAffordance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jsonDataSchemaEClass, JsonDataSchema.class, "JsonDataSchema", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJsonDataSchema_Ld_type(), ecorePackage.getEString(), "ld_type", null, 0, -1, JsonDataSchema.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonDataSchema_Title(), ecorePackage.getEString(), "title", null, 0, 1, JsonDataSchema.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonDataSchema_Description(), ecorePackage.getEString(), "description", null, 0, 1, JsonDataSchema.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonDataSchema_Type(), this.getJsonType(), "type", null, 0, 1, JsonDataSchema.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonDataSchema_Const(), ecorePackage.getEString(), "const", null, 0, 1, JsonDataSchema.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonDataSchema_Unit(), ecorePackage.getEString(), "unit", null, 0, 1, JsonDataSchema.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonDataSchema_Enum(), ecorePackage.getEString(), "enum", null, 0, -1, JsonDataSchema.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonDataSchema_ReadOnly(), this.getJsonBoolean(), "readOnly", null, 0, 1, JsonDataSchema.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonDataSchema_WriteOnly(), this.getJsonBoolean(), "writeOnly", null, 0, 1, JsonDataSchema.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonDataSchema_Format(), ecorePackage.getEString(), "format", null, 0, 1, JsonDataSchema.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonDataSchema_OneOf(), this.getJsonDataSchema(), null, "oneOf", null, 0, -1, JsonDataSchema.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonDataSchema_Titles(), this.getJsonMultiLanguageEntry(), null, "titles", null, 0, -1, JsonDataSchema.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonDataSchema_Descriptions(), this.getJsonMultiLanguageEntry(), null, "descriptions", null, 0, -1, JsonDataSchema.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonDataSchema_MinItems(), ecorePackage.getEInt(), "minItems", null, 0, 1, JsonDataSchema.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonDataSchema_MaxItems(), ecorePackage.getEInt(), "maxItems", null, 0, 1, JsonDataSchema.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonDataSchema_Items(), this.getJsonDataSchema(), null, "items", null, 0, -1, JsonDataSchema.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonDataSchema_Required(), ecorePackage.getEString(), "required", null, 0, -1, JsonDataSchema.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonDataSchema_Properties(), this.getJsonDataSchema(), null, "properties", null, 0, -1, JsonDataSchema.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonDataSchema_Minimum(), ecorePackage.getEInt(), "minimum", null, 0, 1, JsonDataSchema.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonDataSchema_Maximum(), ecorePackage.getEInt(), "maximum", null, 0, 1, JsonDataSchema.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jsonLinkEClass, JsonLink.class, "JsonLink", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJsonLink__href(), ecorePackage.getEString(), "_href", null, 0, 1, JsonLink.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonLink_Type(), ecorePackage.getEString(), "type", null, 0, 1, JsonLink.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonLink_Rel(), ecorePackage.getEString(), "rel", null, 0, 1, JsonLink.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonLink_Anchor(), ecorePackage.getEString(), "anchor", null, 0, 1, JsonLink.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jsonFormEClass, JsonForm.class, "JsonForm", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJsonForm_Ld_type(), ecorePackage.getEString(), "ld_type", null, 0, -1, JsonForm.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonForm_Op(), ecorePackage.getEString(), "op", null, 0, -1, JsonForm.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonForm__href(), ecorePackage.getEString(), "_href", null, 0, 1, JsonForm.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonForm_ContentType(), ecorePackage.getEString(), "contentType", null, 0, 1, JsonForm.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonForm_ContentCoding(), ecorePackage.getEString(), "contentCoding", null, 0, 1, JsonForm.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonForm_Subprotocol(), ecorePackage.getEString(), "subprotocol", null, 0, 1, JsonForm.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonForm_Security(), ecorePackage.getEString(), "security", null, 0, -1, JsonForm.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonForm_Scopes(), ecorePackage.getEString(), "scopes", null, 0, -1, JsonForm.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJsonForm_Response(), this.getJsonExpectedResponse(), null, "response", null, 0, 1, JsonForm.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jsonExpectedResponseEClass, JsonExpectedResponse.class, "JsonExpectedResponse", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJsonExpectedResponse_ContentType(), ecorePackage.getEString(), "contentType", null, 0, 1, JsonExpectedResponse.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jsonMultiLanguageEntryEClass, JsonMultiLanguageEntry.class, "JsonMultiLanguageEntry", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJsonMultiLanguageEntry_Language(), ecorePackage.getEString(), "language", null, 0, 1, JsonMultiLanguageEntry.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJsonMultiLanguageEntry_Content(), ecorePackage.getEString(), "content", null, 0, 1, JsonMultiLanguageEntry.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(jsonBooleanEEnum, JsonBoolean.class, "JsonBoolean");
    addEEnumLiteral(jsonBooleanEEnum, JsonBoolean._FALSE);
    addEEnumLiteral(jsonBooleanEEnum, JsonBoolean._TRUE);

    initEEnum(jsonTypeEEnum, JsonType.class, "JsonType");
    addEEnumLiteral(jsonTypeEEnum, JsonType.STRING);
    addEEnumLiteral(jsonTypeEEnum, JsonType.NUMBER);
    addEEnumLiteral(jsonTypeEEnum, JsonType.INTEGER);
    addEEnumLiteral(jsonTypeEEnum, JsonType.BOOLEAN);
    addEEnumLiteral(jsonTypeEEnum, JsonType.OBJECT);
    addEEnumLiteral(jsonTypeEEnum, JsonType.ARRAY);
    addEEnumLiteral(jsonTypeEEnum, JsonType.NULL);

    // Create resource
    createResource(eNS_URI);
  }

} //ThingDescriptionJsonPackageImpl
