/*
 * generated by Xtext 2.17.0
 */
package edu.uoc.som.wot.td.json.parser.antlr;

import com.google.inject.Inject;
import edu.uoc.som.wot.td.json.parser.antlr.internal.InternalThingDescriptionJsonParser;
import edu.uoc.som.wot.td.json.services.ThingDescriptionJsonGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ThingDescriptionJsonParser extends AbstractAntlrParser {

	@Inject
	private ThingDescriptionJsonGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS");
	}
	

	@Override
	protected InternalThingDescriptionJsonParser createParser(XtextTokenStream stream) {
		return new InternalThingDescriptionJsonParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "JsonThingDescription";
	}

	public ThingDescriptionJsonGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ThingDescriptionJsonGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
