/*
 * generated by Xtext 2.17.0
 */
package edu.uoc.som.wot.td.json.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ThingDescriptionJsonAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("edu/uoc/som/wot/td/json/parser/antlr/internal/InternalThingDescriptionJson.tokens");
	}
}
