/**
 * generated by Xtext 2.17.0
 */
package edu.uoc.som.wot.td.json.thingDescriptionJson;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Json Data Schema</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getLd_type <em>Ld type</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getTitle <em>Title</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getDescription <em>Description</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getType <em>Type</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getConst <em>Const</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getUnit <em>Unit</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getEnum <em>Enum</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getReadOnly <em>Read Only</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getWriteOnly <em>Write Only</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getFormat <em>Format</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getOneOf <em>One Of</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getTitles <em>Titles</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getDescriptions <em>Descriptions</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getMinItems <em>Min Items</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getMaxItems <em>Max Items</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getItems <em>Items</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getRequired <em>Required</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getProperties <em>Properties</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getMinimum <em>Minimum</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getMaximum <em>Maximum</em>}</li>
 * </ul>
 *
 * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonDataSchema()
 * @model
 * @generated
 */
public interface JsonDataSchema extends EObject
{
  /**
   * Returns the value of the '<em><b>Ld type</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ld type</em>' attribute list.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonDataSchema_Ld_type()
   * @model unique="false"
   * @generated
   */
  EList<String> getLd_type();

  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonDataSchema_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonDataSchema_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.JsonType
   * @see #setType(JsonType)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonDataSchema_Type()
   * @model
   * @generated
   */
  JsonType getType();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.JsonType
   * @see #getType()
   * @generated
   */
  void setType(JsonType value);

  /**
   * Returns the value of the '<em><b>Const</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Const</em>' attribute.
   * @see #setConst(String)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonDataSchema_Const()
   * @model
   * @generated
   */
  String getConst();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getConst <em>Const</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Const</em>' attribute.
   * @see #getConst()
   * @generated
   */
  void setConst(String value);

  /**
   * Returns the value of the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unit</em>' attribute.
   * @see #setUnit(String)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonDataSchema_Unit()
   * @model
   * @generated
   */
  String getUnit();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getUnit <em>Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unit</em>' attribute.
   * @see #getUnit()
   * @generated
   */
  void setUnit(String value);

  /**
   * Returns the value of the '<em><b>Enum</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enum</em>' attribute list.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonDataSchema_Enum()
   * @model unique="false"
   * @generated
   */
  EList<String> getEnum();

  /**
   * Returns the value of the '<em><b>Read Only</b></em>' attribute.
   * The literals are from the enumeration {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonBoolean}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Read Only</em>' attribute.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.JsonBoolean
   * @see #setReadOnly(JsonBoolean)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonDataSchema_ReadOnly()
   * @model
   * @generated
   */
  JsonBoolean getReadOnly();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getReadOnly <em>Read Only</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Read Only</em>' attribute.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.JsonBoolean
   * @see #getReadOnly()
   * @generated
   */
  void setReadOnly(JsonBoolean value);

  /**
   * Returns the value of the '<em><b>Write Only</b></em>' attribute.
   * The literals are from the enumeration {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonBoolean}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Write Only</em>' attribute.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.JsonBoolean
   * @see #setWriteOnly(JsonBoolean)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonDataSchema_WriteOnly()
   * @model
   * @generated
   */
  JsonBoolean getWriteOnly();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getWriteOnly <em>Write Only</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Write Only</em>' attribute.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.JsonBoolean
   * @see #getWriteOnly()
   * @generated
   */
  void setWriteOnly(JsonBoolean value);

  /**
   * Returns the value of the '<em><b>Format</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Format</em>' attribute.
   * @see #setFormat(String)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonDataSchema_Format()
   * @model
   * @generated
   */
  String getFormat();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getFormat <em>Format</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Format</em>' attribute.
   * @see #getFormat()
   * @generated
   */
  void setFormat(String value);

  /**
   * Returns the value of the '<em><b>One Of</b></em>' containment reference list.
   * The list contents are of type {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>One Of</em>' containment reference list.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonDataSchema_OneOf()
   * @model containment="true"
   * @generated
   */
  EList<JsonDataSchema> getOneOf();

  /**
   * Returns the value of the '<em><b>Titles</b></em>' containment reference list.
   * The list contents are of type {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonMultiLanguageEntry}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Titles</em>' containment reference list.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonDataSchema_Titles()
   * @model containment="true"
   * @generated
   */
  EList<JsonMultiLanguageEntry> getTitles();

  /**
   * Returns the value of the '<em><b>Descriptions</b></em>' containment reference list.
   * The list contents are of type {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonMultiLanguageEntry}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Descriptions</em>' containment reference list.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonDataSchema_Descriptions()
   * @model containment="true"
   * @generated
   */
  EList<JsonMultiLanguageEntry> getDescriptions();

  /**
   * Returns the value of the '<em><b>Min Items</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Min Items</em>' attribute.
   * @see #setMinItems(int)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonDataSchema_MinItems()
   * @model
   * @generated
   */
  int getMinItems();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getMinItems <em>Min Items</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Min Items</em>' attribute.
   * @see #getMinItems()
   * @generated
   */
  void setMinItems(int value);

  /**
   * Returns the value of the '<em><b>Max Items</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max Items</em>' attribute.
   * @see #setMaxItems(int)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonDataSchema_MaxItems()
   * @model
   * @generated
   */
  int getMaxItems();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getMaxItems <em>Max Items</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max Items</em>' attribute.
   * @see #getMaxItems()
   * @generated
   */
  void setMaxItems(int value);

  /**
   * Returns the value of the '<em><b>Items</b></em>' containment reference list.
   * The list contents are of type {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Items</em>' containment reference list.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonDataSchema_Items()
   * @model containment="true"
   * @generated
   */
  EList<JsonDataSchema> getItems();

  /**
   * Returns the value of the '<em><b>Required</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Required</em>' attribute list.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonDataSchema_Required()
   * @model unique="false"
   * @generated
   */
  EList<String> getRequired();

  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonDataSchema_Properties()
   * @model containment="true"
   * @generated
   */
  EList<JsonDataSchema> getProperties();

  /**
   * Returns the value of the '<em><b>Minimum</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Minimum</em>' attribute.
   * @see #setMinimum(int)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonDataSchema_Minimum()
   * @model
   * @generated
   */
  int getMinimum();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getMinimum <em>Minimum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Minimum</em>' attribute.
   * @see #getMinimum()
   * @generated
   */
  void setMinimum(int value);

  /**
   * Returns the value of the '<em><b>Maximum</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Maximum</em>' attribute.
   * @see #setMaximum(int)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonDataSchema_Maximum()
   * @model
   * @generated
   */
  int getMaximum();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema#getMaximum <em>Maximum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Maximum</em>' attribute.
   * @see #getMaximum()
   * @generated
   */
  void setMaximum(int value);

} // JsonDataSchema
