/**
 * generated by Xtext 2.17.0
 */
package edu.uoc.som.wot.td.json.thingDescriptionJson;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Json Event Affordance</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonEventAffordance#getId <em>Id</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonEventAffordance#getData <em>Data</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonEventAffordance#getSubscription <em>Subscription</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonEventAffordance#getCancellation <em>Cancellation</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonEventAffordance#getLd_type <em>Ld type</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonEventAffordance#getTitle <em>Title</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonEventAffordance#getDescription <em>Description</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonEventAffordance#getForms <em>Forms</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonEventAffordance#getTitles <em>Titles</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonEventAffordance#getDescriptions <em>Descriptions</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonEventAffordance#getUriVariable <em>Uri Variable</em>}</li>
 * </ul>
 *
 * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonEventAffordance()
 * @model
 * @generated
 */
public interface JsonEventAffordance extends EObject
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonEventAffordance_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonEventAffordance#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Data</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data</em>' containment reference.
   * @see #setData(JsonDataSchema)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonEventAffordance_Data()
   * @model containment="true"
   * @generated
   */
  JsonDataSchema getData();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonEventAffordance#getData <em>Data</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data</em>' containment reference.
   * @see #getData()
   * @generated
   */
  void setData(JsonDataSchema value);

  /**
   * Returns the value of the '<em><b>Subscription</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subscription</em>' containment reference.
   * @see #setSubscription(JsonDataSchema)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonEventAffordance_Subscription()
   * @model containment="true"
   * @generated
   */
  JsonDataSchema getSubscription();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonEventAffordance#getSubscription <em>Subscription</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Subscription</em>' containment reference.
   * @see #getSubscription()
   * @generated
   */
  void setSubscription(JsonDataSchema value);

  /**
   * Returns the value of the '<em><b>Cancellation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cancellation</em>' containment reference.
   * @see #setCancellation(JsonDataSchema)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonEventAffordance_Cancellation()
   * @model containment="true"
   * @generated
   */
  JsonDataSchema getCancellation();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonEventAffordance#getCancellation <em>Cancellation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cancellation</em>' containment reference.
   * @see #getCancellation()
   * @generated
   */
  void setCancellation(JsonDataSchema value);

  /**
   * Returns the value of the '<em><b>Ld type</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ld type</em>' attribute list.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonEventAffordance_Ld_type()
   * @model unique="false"
   * @generated
   */
  EList<String> getLd_type();

  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonEventAffordance_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonEventAffordance#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonEventAffordance_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonEventAffordance#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Forms</b></em>' containment reference list.
   * The list contents are of type {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonForm}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Forms</em>' containment reference list.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonEventAffordance_Forms()
   * @model containment="true"
   * @generated
   */
  EList<JsonForm> getForms();

  /**
   * Returns the value of the '<em><b>Titles</b></em>' containment reference list.
   * The list contents are of type {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonMultiLanguageEntry}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Titles</em>' containment reference list.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonEventAffordance_Titles()
   * @model containment="true"
   * @generated
   */
  EList<JsonMultiLanguageEntry> getTitles();

  /**
   * Returns the value of the '<em><b>Descriptions</b></em>' containment reference list.
   * The list contents are of type {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonMultiLanguageEntry}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Descriptions</em>' containment reference list.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonEventAffordance_Descriptions()
   * @model containment="true"
   * @generated
   */
  EList<JsonMultiLanguageEntry> getDescriptions();

  /**
   * Returns the value of the '<em><b>Uri Variable</b></em>' containment reference list.
   * The list contents are of type {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Uri Variable</em>' containment reference list.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonEventAffordance_UriVariable()
   * @model containment="true"
   * @generated
   */
  EList<JsonDataSchema> getUriVariable();

} // JsonEventAffordance
