/**
 * generated by Xtext 2.17.0
 */
package edu.uoc.som.wot.td.json.thingDescriptionJson;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Json Action Affordance</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonActionAffordance#getId <em>Id</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonActionAffordance#getSafe <em>Safe</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonActionAffordance#getIdempotent <em>Idempotent</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonActionAffordance#getInput <em>Input</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonActionAffordance#getOutput <em>Output</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonActionAffordance#getLd_type <em>Ld type</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonActionAffordance#getTitle <em>Title</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonActionAffordance#getDescription <em>Description</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonActionAffordance#getForms <em>Forms</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonActionAffordance#getTitles <em>Titles</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonActionAffordance#getDescriptions <em>Descriptions</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonActionAffordance#getUriVariable <em>Uri Variable</em>}</li>
 * </ul>
 *
 * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonActionAffordance()
 * @model
 * @generated
 */
public interface JsonActionAffordance extends EObject
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonActionAffordance_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonActionAffordance#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Safe</b></em>' attribute.
   * The literals are from the enumeration {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonBoolean}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Safe</em>' attribute.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.JsonBoolean
   * @see #setSafe(JsonBoolean)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonActionAffordance_Safe()
   * @model
   * @generated
   */
  JsonBoolean getSafe();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonActionAffordance#getSafe <em>Safe</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Safe</em>' attribute.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.JsonBoolean
   * @see #getSafe()
   * @generated
   */
  void setSafe(JsonBoolean value);

  /**
   * Returns the value of the '<em><b>Idempotent</b></em>' attribute.
   * The literals are from the enumeration {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonBoolean}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Idempotent</em>' attribute.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.JsonBoolean
   * @see #setIdempotent(JsonBoolean)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonActionAffordance_Idempotent()
   * @model
   * @generated
   */
  JsonBoolean getIdempotent();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonActionAffordance#getIdempotent <em>Idempotent</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Idempotent</em>' attribute.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.JsonBoolean
   * @see #getIdempotent()
   * @generated
   */
  void setIdempotent(JsonBoolean value);

  /**
   * Returns the value of the '<em><b>Input</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input</em>' containment reference.
   * @see #setInput(JsonDataSchema)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonActionAffordance_Input()
   * @model containment="true"
   * @generated
   */
  JsonDataSchema getInput();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonActionAffordance#getInput <em>Input</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Input</em>' containment reference.
   * @see #getInput()
   * @generated
   */
  void setInput(JsonDataSchema value);

  /**
   * Returns the value of the '<em><b>Output</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Output</em>' containment reference.
   * @see #setOutput(JsonDataSchema)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonActionAffordance_Output()
   * @model containment="true"
   * @generated
   */
  JsonDataSchema getOutput();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonActionAffordance#getOutput <em>Output</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Output</em>' containment reference.
   * @see #getOutput()
   * @generated
   */
  void setOutput(JsonDataSchema value);

  /**
   * Returns the value of the '<em><b>Ld type</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ld type</em>' attribute list.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonActionAffordance_Ld_type()
   * @model unique="false"
   * @generated
   */
  EList<String> getLd_type();

  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonActionAffordance_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonActionAffordance#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonActionAffordance_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonActionAffordance#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Forms</b></em>' containment reference list.
   * The list contents are of type {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonForm}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Forms</em>' containment reference list.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonActionAffordance_Forms()
   * @model containment="true"
   * @generated
   */
  EList<JsonForm> getForms();

  /**
   * Returns the value of the '<em><b>Titles</b></em>' containment reference list.
   * The list contents are of type {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonMultiLanguageEntry}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Titles</em>' containment reference list.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonActionAffordance_Titles()
   * @model containment="true"
   * @generated
   */
  EList<JsonMultiLanguageEntry> getTitles();

  /**
   * Returns the value of the '<em><b>Descriptions</b></em>' containment reference list.
   * The list contents are of type {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonMultiLanguageEntry}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Descriptions</em>' containment reference list.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonActionAffordance_Descriptions()
   * @model containment="true"
   * @generated
   */
  EList<JsonMultiLanguageEntry> getDescriptions();

  /**
   * Returns the value of the '<em><b>Uri Variable</b></em>' containment reference list.
   * The list contents are of type {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Uri Variable</em>' containment reference list.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonActionAffordance_UriVariable()
   * @model containment="true"
   * @generated
   */
  EList<JsonDataSchema> getUriVariable();

} // JsonActionAffordance
