/**
 * generated by Xtext 2.17.0
 */
package edu.uoc.som.wot.td.json.thingDescriptionJson;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Json Link</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonLink#get_href <em>href</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonLink#getType <em>Type</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonLink#getRel <em>Rel</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonLink#getAnchor <em>Anchor</em>}</li>
 * </ul>
 *
 * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonLink()
 * @model
 * @generated
 */
public interface JsonLink extends EObject
{
  /**
   * Returns the value of the '<em><b>href</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>href</em>' attribute.
   * @see #set_href(String)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonLink__href()
   * @model
   * @generated
   */
  String get_href();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonLink#get_href <em>href</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>href</em>' attribute.
   * @see #get_href()
   * @generated
   */
  void set_href(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonLink_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonLink#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Rel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rel</em>' attribute.
   * @see #setRel(String)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonLink_Rel()
   * @model
   * @generated
   */
  String getRel();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonLink#getRel <em>Rel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rel</em>' attribute.
   * @see #getRel()
   * @generated
   */
  void setRel(String value);

  /**
   * Returns the value of the '<em><b>Anchor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Anchor</em>' attribute.
   * @see #setAnchor(String)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonLink_Anchor()
   * @model
   * @generated
   */
  String getAnchor();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonLink#getAnchor <em>Anchor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Anchor</em>' attribute.
   * @see #getAnchor()
   * @generated
   */
  void setAnchor(String value);

} // JsonLink
