/**
 * generated by Xtext 2.17.0
 */
package edu.uoc.som.wot.td.json.thingDescriptionJson;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Json Expected Response</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonExpectedResponse#getContentType <em>Content Type</em>}</li>
 * </ul>
 *
 * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonExpectedResponse()
 * @model
 * @generated
 */
public interface JsonExpectedResponse extends EObject
{
  /**
   * Returns the value of the '<em><b>Content Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Content Type</em>' attribute.
   * @see #setContentType(String)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonExpectedResponse_ContentType()
   * @model
   * @generated
   */
  String getContentType();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonExpectedResponse#getContentType <em>Content Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Content Type</em>' attribute.
   * @see #getContentType()
   * @generated
   */
  void setContentType(String value);

} // JsonExpectedResponse
