/**
 * generated by Xtext 2.17.0
 */
package edu.uoc.som.wot.td.json.thingDescriptionJson;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Json Property Affordance</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getId <em>Id</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getObservable <em>Observable</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getLd_type <em>Ld type</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getTitle <em>Title</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getDescription <em>Description</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getTitles <em>Titles</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getDescriptions <em>Descriptions</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getForms <em>Forms</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getUriVariable <em>Uri Variable</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getType <em>Type</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getConst <em>Const</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getUnit <em>Unit</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getEnum <em>Enum</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getReadOnly <em>Read Only</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getWriteOnly <em>Write Only</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getFormat <em>Format</em>}</li>
 *   <li>{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getOneOf <em>One Of</em>}</li>
 * </ul>
 *
 * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonPropertyAffordance()
 * @model
 * @generated
 */
public interface JsonPropertyAffordance extends EObject
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonPropertyAffordance_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Observable</b></em>' attribute.
   * The literals are from the enumeration {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonBoolean}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Observable</em>' attribute.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.JsonBoolean
   * @see #setObservable(JsonBoolean)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonPropertyAffordance_Observable()
   * @model
   * @generated
   */
  JsonBoolean getObservable();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getObservable <em>Observable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Observable</em>' attribute.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.JsonBoolean
   * @see #getObservable()
   * @generated
   */
  void setObservable(JsonBoolean value);

  /**
   * Returns the value of the '<em><b>Ld type</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ld type</em>' attribute list.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonPropertyAffordance_Ld_type()
   * @model unique="false"
   * @generated
   */
  EList<String> getLd_type();

  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonPropertyAffordance_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonPropertyAffordance_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Titles</b></em>' containment reference list.
   * The list contents are of type {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonMultiLanguageEntry}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Titles</em>' containment reference list.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonPropertyAffordance_Titles()
   * @model containment="true"
   * @generated
   */
  EList<JsonMultiLanguageEntry> getTitles();

  /**
   * Returns the value of the '<em><b>Descriptions</b></em>' containment reference list.
   * The list contents are of type {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonMultiLanguageEntry}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Descriptions</em>' containment reference list.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonPropertyAffordance_Descriptions()
   * @model containment="true"
   * @generated
   */
  EList<JsonMultiLanguageEntry> getDescriptions();

  /**
   * Returns the value of the '<em><b>Forms</b></em>' containment reference list.
   * The list contents are of type {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonForm}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Forms</em>' containment reference list.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonPropertyAffordance_Forms()
   * @model containment="true"
   * @generated
   */
  EList<JsonForm> getForms();

  /**
   * Returns the value of the '<em><b>Uri Variable</b></em>' containment reference list.
   * The list contents are of type {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Uri Variable</em>' containment reference list.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonPropertyAffordance_UriVariable()
   * @model containment="true"
   * @generated
   */
  EList<JsonDataSchema> getUriVariable();

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.JsonType
   * @see #setType(JsonType)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonPropertyAffordance_Type()
   * @model
   * @generated
   */
  JsonType getType();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.JsonType
   * @see #getType()
   * @generated
   */
  void setType(JsonType value);

  /**
   * Returns the value of the '<em><b>Const</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Const</em>' attribute.
   * @see #setConst(String)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonPropertyAffordance_Const()
   * @model
   * @generated
   */
  String getConst();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getConst <em>Const</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Const</em>' attribute.
   * @see #getConst()
   * @generated
   */
  void setConst(String value);

  /**
   * Returns the value of the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unit</em>' attribute.
   * @see #setUnit(String)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonPropertyAffordance_Unit()
   * @model
   * @generated
   */
  String getUnit();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getUnit <em>Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unit</em>' attribute.
   * @see #getUnit()
   * @generated
   */
  void setUnit(String value);

  /**
   * Returns the value of the '<em><b>Enum</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enum</em>' attribute list.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonPropertyAffordance_Enum()
   * @model unique="false"
   * @generated
   */
  EList<String> getEnum();

  /**
   * Returns the value of the '<em><b>Read Only</b></em>' attribute.
   * The literals are from the enumeration {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonBoolean}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Read Only</em>' attribute.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.JsonBoolean
   * @see #setReadOnly(JsonBoolean)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonPropertyAffordance_ReadOnly()
   * @model
   * @generated
   */
  JsonBoolean getReadOnly();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getReadOnly <em>Read Only</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Read Only</em>' attribute.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.JsonBoolean
   * @see #getReadOnly()
   * @generated
   */
  void setReadOnly(JsonBoolean value);

  /**
   * Returns the value of the '<em><b>Write Only</b></em>' attribute.
   * The literals are from the enumeration {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonBoolean}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Write Only</em>' attribute.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.JsonBoolean
   * @see #setWriteOnly(JsonBoolean)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonPropertyAffordance_WriteOnly()
   * @model
   * @generated
   */
  JsonBoolean getWriteOnly();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getWriteOnly <em>Write Only</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Write Only</em>' attribute.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.JsonBoolean
   * @see #getWriteOnly()
   * @generated
   */
  void setWriteOnly(JsonBoolean value);

  /**
   * Returns the value of the '<em><b>Format</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Format</em>' attribute.
   * @see #setFormat(String)
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonPropertyAffordance_Format()
   * @model
   * @generated
   */
  String getFormat();

  /**
   * Sets the value of the '{@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonPropertyAffordance#getFormat <em>Format</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Format</em>' attribute.
   * @see #getFormat()
   * @generated
   */
  void setFormat(String value);

  /**
   * Returns the value of the '<em><b>One Of</b></em>' containment reference list.
   * The list contents are of type {@link edu.uoc.som.wot.td.json.thingDescriptionJson.JsonDataSchema}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>One Of</em>' containment reference list.
   * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage#getJsonPropertyAffordance_OneOf()
   * @model containment="true"
   * @generated
   */
  EList<JsonDataSchema> getOneOf();

} // JsonPropertyAffordance
