/**
 * generated by Xtext 2.17.0
 */
package edu.uoc.som.wot.td.json.thingDescriptionJson;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see edu.uoc.som.wot.td.json.thingDescriptionJson.ThingDescriptionJsonPackage
 * @generated
 */
public interface ThingDescriptionJsonFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ThingDescriptionJsonFactory eINSTANCE = edu.uoc.som.wot.td.json.thingDescriptionJson.impl.ThingDescriptionJsonFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Json Thing Description</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Json Thing Description</em>'.
   * @generated
   */
  JsonThingDescription createJsonThingDescription();

  /**
   * Returns a new object of class '<em>Json Version Info</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Json Version Info</em>'.
   * @generated
   */
  JsonVersionInfo createJsonVersionInfo();

  /**
   * Returns a new object of class '<em>Json Security Scheme</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Json Security Scheme</em>'.
   * @generated
   */
  JsonSecurityScheme createJsonSecurityScheme();

  /**
   * Returns a new object of class '<em>Json Property Affordance</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Json Property Affordance</em>'.
   * @generated
   */
  JsonPropertyAffordance createJsonPropertyAffordance();

  /**
   * Returns a new object of class '<em>Json Action Affordance</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Json Action Affordance</em>'.
   * @generated
   */
  JsonActionAffordance createJsonActionAffordance();

  /**
   * Returns a new object of class '<em>Json Event Affordance</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Json Event Affordance</em>'.
   * @generated
   */
  JsonEventAffordance createJsonEventAffordance();

  /**
   * Returns a new object of class '<em>Json Data Schema</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Json Data Schema</em>'.
   * @generated
   */
  JsonDataSchema createJsonDataSchema();

  /**
   * Returns a new object of class '<em>Json Link</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Json Link</em>'.
   * @generated
   */
  JsonLink createJsonLink();

  /**
   * Returns a new object of class '<em>Json Form</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Json Form</em>'.
   * @generated
   */
  JsonForm createJsonForm();

  /**
   * Returns a new object of class '<em>Json Expected Response</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Json Expected Response</em>'.
   * @generated
   */
  JsonExpectedResponse createJsonExpectedResponse();

  /**
   * Returns a new object of class '<em>Json Multi Language Entry</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Json Multi Language Entry</em>'.
   * @generated
   */
  JsonMultiLanguageEntry createJsonMultiLanguageEntry();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  ThingDescriptionJsonPackage getThingDescriptionJsonPackage();

} //ThingDescriptionJsonFactory
