/*
 * generated by Xtext 2.17.0
 */
package edu.uoc.som.wot.td.json.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractThingDescriptionJsonScopeProvider extends DelegatingScopeProvider {
}
