/*
 * generated by Xtext 2.17.0
 */
package edu.uoc.som.wot.td.json


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ThingDescriptionJsonRuntimeModule extends AbstractThingDescriptionJsonRuntimeModule {
	override bindIValueConverterService() {
		CustomStringConverters
	}
}
